#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/uia/events
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/utils.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/utils.js
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xdc.tci:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xdc.tci
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/template.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/template.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/om2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/om2.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen2.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/Warnings.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/Warnings.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/IPackage.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/IPackage.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/package.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Clock.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Clock.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Trace.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Trace.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/bld.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/bld.js
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/BuildEnvironment.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/PackageContents.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/_gen.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Library.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Executable.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Repository.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Configuration.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Configuration.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Script.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Script.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Manifest.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Manifest.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Utils.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget2.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget3.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget3.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITargetFilter.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/uia_2_00_02_39/uia.bld:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/uia_2_00_02_39/uia.bld
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_large.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_large.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_float.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_float.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/IArm.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/_utils.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/_utils.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Linux86.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Linux86.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Mingw.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Mingw.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv6.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv7A.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/IM.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/IM.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M3.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M3.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A8F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A8F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A9F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A9F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A15F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A15F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/package.xs
package.mak: package.bld
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/uia_2_00_02_39/packages/ti/uia/build/common.bld:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/uia_2_00_02_39/packages/ti/uia/build/common.bld
endif

ti.targets.arm.elf.M3.rootDir ?= /db/vendors/ti/arm/5.2.2/Linux
ti.targets.arm.elf.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/
ti.targets.arm.elf.M4.rootDir ?= /db/vendors/ti/arm/5.2.2/Linux
gnu.targets.arm.M3.rootDir ?= /db/vendors/linaro/gcc-arm-none-eabi-4_8-2014q3
gnu.targets.arm.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/
gnu.targets.arm.M4.rootDir ?= /db/vendors/linaro/gcc-arm-none-eabi-4_8-2014q3
iar.targets.arm.M3.rootDir ?= /db/vendors/iar/arm/7.40.1a/Linux
iar.targets.arm.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/
iar.targets.arm.M4.rootDir ?= /db/vendors/iar/arm/7.40.1a/Linux
.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3

.PRECIOUS: $(XDCCFGDIR)/%.oem4
.PHONY: all,em4 .dlls,em4 .executables,em4 test,em4
all,em4: .executables,em4
.executables,em4: .libraries,em4
.executables,em4: .dlls,em4
.dlls,em4: .libraries,em4
.libraries,em4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4
	@$(ECHO) xdc .executables,em4
	@$(ECHO) xdc .libraries,em4
	@$(ECHO) xdc .dlls,em4

.PRECIOUS: $(XDCCFGDIR)/%.om3g
.PHONY: all,m3g .dlls,m3g .executables,m3g test,m3g
all,m3g: .executables,m3g
.executables,m3g: .libraries,m3g
.executables,m3g: .dlls,m3g
.dlls,m3g: .libraries,m3g
.libraries,m3g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m3g
	@$(ECHO) xdc .executables,m3g
	@$(ECHO) xdc .libraries,m3g
	@$(ECHO) xdc .dlls,m3g

.PRECIOUS: $(XDCCFGDIR)/%.om4g
.PHONY: all,m4g .dlls,m4g .executables,m4g test,m4g
all,m4g: .executables,m4g
.executables,m4g: .libraries,m4g
.executables,m4g: .dlls,m4g
.dlls,m4g: .libraries,m4g
.libraries,m4g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4g
	@$(ECHO) xdc .executables,m4g
	@$(ECHO) xdc .libraries,m4g
	@$(ECHO) xdc .dlls,m4g

.PRECIOUS: $(XDCCFGDIR)/%.orm3
.PHONY: all,rm3 .dlls,rm3 .executables,rm3 test,rm3
all,rm3: .executables,rm3
.executables,rm3: .libraries,rm3
.executables,rm3: .dlls,rm3
.dlls,rm3: .libraries,rm3
.libraries,rm3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm3
	@$(ECHO) xdc .executables,rm3
	@$(ECHO) xdc .libraries,rm3
	@$(ECHO) xdc .dlls,rm3

.PRECIOUS: $(XDCCFGDIR)/%.orm4
.PHONY: all,rm4 .dlls,rm4 .executables,rm4 test,rm4
all,rm4: .executables,rm4
.executables,rm4: .libraries,rm4
.executables,rm4: .dlls,rm4
.dlls,rm4: .libraries,rm4
.libraries,rm4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm4
	@$(ECHO) xdc .executables,rm4
	@$(ECHO) xdc .libraries,rm4
	@$(ECHO) xdc .dlls,rm4


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.uia.events.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.uia.events" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.uia.events $@

.libraries,em3 .libraries: lib/release/ti.uia.events.aem3

-include lib/release/ti.uia.events.aem3.mak
lib/release/ti.uia.events.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.oem3 package/lib/lib/release/ti.uia.events/UIAAppCtx.oem3 package/lib/lib/release/ti.uia.events/UIAChanCtx.oem3 package/lib/lib/release/ti.uia.events/UIAFrameCtx.oem3 package/lib/lib/release/ti.uia.events/UIAThreadCtx.oem3 package/lib/lib/release/ti.uia.events/UIAUserCtx.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.oem3 package/lib/lib/release/ti.uia.events/UIAAppCtx.oem3 package/lib/lib/release/ti.uia.events/UIAChanCtx.oem3 package/lib/lib/release/ti.uia.events/UIAFrameCtx.oem3 package/lib/lib/release/ti.uia.events/UIAThreadCtx.oem3 package/lib/lib/release/ti.uia.events/UIAUserCtx.oem3 
lib/release/ti.uia.events.aem3: export C_DIR=
lib/release/ti.uia.events.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/release/ti.uia.events.aem3
.libraries,em4 .libraries: lib/release/ti.uia.events.aem4

-include lib/release/ti.uia.events.aem4.mak
lib/release/ti.uia.events.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.oem4 package/lib/lib/release/ti.uia.events/UIAAppCtx.oem4 package/lib/lib/release/ti.uia.events/UIAChanCtx.oem4 package/lib/lib/release/ti.uia.events/UIAFrameCtx.oem4 package/lib/lib/release/ti.uia.events/UIAThreadCtx.oem4 package/lib/lib/release/ti.uia.events/UIAUserCtx.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.oem4 package/lib/lib/release/ti.uia.events/UIAAppCtx.oem4 package/lib/lib/release/ti.uia.events/UIAChanCtx.oem4 package/lib/lib/release/ti.uia.events/UIAFrameCtx.oem4 package/lib/lib/release/ti.uia.events/UIAThreadCtx.oem4 package/lib/lib/release/ti.uia.events/UIAUserCtx.oem4 
lib/release/ti.uia.events.aem4: export C_DIR=
lib/release/ti.uia.events.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/release/ti.uia.events.aem4
.libraries,m3g .libraries: lib/release/ti.uia.events.am3g

-include lib/release/ti.uia.events.am3g.mak
lib/release/ti.uia.events.am3g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.om3g package/lib/lib/release/ti.uia.events/UIAAppCtx.om3g package/lib/lib/release/ti.uia.events/UIAChanCtx.om3g package/lib/lib/release/ti.uia.events/UIAFrameCtx.om3g package/lib/lib/release/ti.uia.events/UIAThreadCtx.om3g package/lib/lib/release/ti.uia.events/UIAUserCtx.om3g  into $@ ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.om3g package/lib/lib/release/ti.uia.events/UIAAppCtx.om3g package/lib/lib/release/ti.uia.events/UIAChanCtx.om3g package/lib/lib/release/ti.uia.events/UIAFrameCtx.om3g package/lib/lib/release/ti.uia.events/UIAThreadCtx.om3g package/lib/lib/release/ti.uia.events/UIAUserCtx.om3g 
lib/release/ti.uia.events.am3g: export LD_LIBRARY_PATH=

clean,m3g clean::
	-$(RM) lib/release/ti.uia.events.am3g
.libraries,m4g .libraries: lib/release/ti.uia.events.am4g

-include lib/release/ti.uia.events.am4g.mak
lib/release/ti.uia.events.am4g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.om4g package/lib/lib/release/ti.uia.events/UIAAppCtx.om4g package/lib/lib/release/ti.uia.events/UIAChanCtx.om4g package/lib/lib/release/ti.uia.events/UIAFrameCtx.om4g package/lib/lib/release/ti.uia.events/UIAThreadCtx.om4g package/lib/lib/release/ti.uia.events/UIAUserCtx.om4g  into $@ ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.om4g package/lib/lib/release/ti.uia.events/UIAAppCtx.om4g package/lib/lib/release/ti.uia.events/UIAChanCtx.om4g package/lib/lib/release/ti.uia.events/UIAFrameCtx.om4g package/lib/lib/release/ti.uia.events/UIAThreadCtx.om4g package/lib/lib/release/ti.uia.events/UIAUserCtx.om4g 
lib/release/ti.uia.events.am4g: export LD_LIBRARY_PATH=

clean,m4g clean::
	-$(RM) lib/release/ti.uia.events.am4g
.libraries,rm3 .libraries: lib/release/ti.uia.events.arm3

-include lib/release/ti.uia.events.arm3.mak
lib/release/ti.uia.events.arm3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.orm3 package/lib/lib/release/ti.uia.events/UIAAppCtx.orm3 package/lib/lib/release/ti.uia.events/UIAChanCtx.orm3 package/lib/lib/release/ti.uia.events/UIAFrameCtx.orm3 package/lib/lib/release/ti.uia.events/UIAThreadCtx.orm3 package/lib/lib/release/ti.uia.events/UIAUserCtx.orm3  into $@ ...
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.orm3 package/lib/lib/release/ti.uia.events/UIAAppCtx.orm3 package/lib/lib/release/ti.uia.events/UIAChanCtx.orm3 package/lib/lib/release/ti.uia.events/UIAFrameCtx.orm3 package/lib/lib/release/ti.uia.events/UIAThreadCtx.orm3 package/lib/lib/release/ti.uia.events/UIAUserCtx.orm3 

clean,rm3 clean::
	-$(RM) lib/release/ti.uia.events.arm3
.libraries,rm4 .libraries: lib/release/ti.uia.events.arm4

-include lib/release/ti.uia.events.arm4.mak
lib/release/ti.uia.events.arm4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.orm4 package/lib/lib/release/ti.uia.events/UIAAppCtx.orm4 package/lib/lib/release/ti.uia.events/UIAChanCtx.orm4 package/lib/lib/release/ti.uia.events/UIAFrameCtx.orm4 package/lib/lib/release/ti.uia.events/UIAThreadCtx.orm4 package/lib/lib/release/ti.uia.events/UIAUserCtx.orm4  into $@ ...
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.orm4 package/lib/lib/release/ti.uia.events/UIAAppCtx.orm4 package/lib/lib/release/ti.uia.events/UIAChanCtx.orm4 package/lib/lib/release/ti.uia.events/UIAFrameCtx.orm4 package/lib/lib/release/ti.uia.events/UIAThreadCtx.orm4 package/lib/lib/release/ti.uia.events/UIAUserCtx.orm4 

clean,rm4 clean::
	-$(RM) lib/release/ti.uia.events.arm4
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
package_ti.uia.events.oem3,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.oem3
package_ti.uia.events.sem3,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.sem3
UIAAppCtx.oem3,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.oem3
UIAAppCtx.sem3,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.sem3
UIAChanCtx.oem3,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.oem3
UIAChanCtx.sem3,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.sem3
UIAFrameCtx.oem3,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.oem3
UIAFrameCtx.sem3,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.sem3
UIAThreadCtx.oem3,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.oem3
UIAThreadCtx.sem3,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.sem3
UIAUserCtx.oem3,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.oem3
UIAUserCtx.sem3,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.sem3
package_ti.uia.events.oem4,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.oem4
package_ti.uia.events.sem4,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.sem4
UIAAppCtx.oem4,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.oem4
UIAAppCtx.sem4,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.sem4
UIAChanCtx.oem4,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.oem4
UIAChanCtx.sem4,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.sem4
UIAFrameCtx.oem4,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.oem4
UIAFrameCtx.sem4,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.sem4
UIAThreadCtx.oem4,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.oem4
UIAThreadCtx.sem4,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.sem4
UIAUserCtx.oem4,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.oem4
UIAUserCtx.sem4,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.sem4
package_ti.uia.events.om3g,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.om3g
package_ti.uia.events.sm3g,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.sm3g
UIAAppCtx.om3g,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.om3g
UIAAppCtx.sm3g,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.sm3g
UIAChanCtx.om3g,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.om3g
UIAChanCtx.sm3g,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.sm3g
UIAFrameCtx.om3g,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.om3g
UIAFrameCtx.sm3g,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.sm3g
UIAThreadCtx.om3g,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.om3g
UIAThreadCtx.sm3g,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.sm3g
UIAUserCtx.om3g,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.om3g
UIAUserCtx.sm3g,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.sm3g
package_ti.uia.events.om4g,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.om4g
package_ti.uia.events.sm4g,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.sm4g
UIAAppCtx.om4g,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.om4g
UIAAppCtx.sm4g,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.sm4g
UIAChanCtx.om4g,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.om4g
UIAChanCtx.sm4g,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.sm4g
UIAFrameCtx.om4g,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.om4g
UIAFrameCtx.sm4g,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.sm4g
UIAThreadCtx.om4g,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.om4g
UIAThreadCtx.sm4g,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.sm4g
UIAUserCtx.om4g,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.om4g
UIAUserCtx.sm4g,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.sm4g
package_ti.uia.events.orm3,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.orm3
package_ti.uia.events.srm3,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.srm3
UIAAppCtx.orm3,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.orm3
UIAAppCtx.srm3,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.srm3
UIAChanCtx.orm3,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.orm3
UIAChanCtx.srm3,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.srm3
UIAFrameCtx.orm3,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.orm3
UIAFrameCtx.srm3,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.srm3
UIAThreadCtx.orm3,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.orm3
UIAThreadCtx.srm3,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.srm3
UIAUserCtx.orm3,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.orm3
UIAUserCtx.srm3,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.srm3
package_ti.uia.events.orm4,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.orm4
package_ti.uia.events.srm4,copy : package/lib/lib/release/ti.uia.events/package/package_ti.uia.events.srm4
UIAAppCtx.orm4,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.orm4
UIAAppCtx.srm4,copy : package/lib/lib/release/ti.uia.events/UIAAppCtx.srm4
UIAChanCtx.orm4,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.orm4
UIAChanCtx.srm4,copy : package/lib/lib/release/ti.uia.events/UIAChanCtx.srm4
UIAFrameCtx.orm4,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.orm4
UIAFrameCtx.srm4,copy : package/lib/lib/release/ti.uia.events/UIAFrameCtx.srm4
UIAThreadCtx.orm4,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.orm4
UIAThreadCtx.srm4,copy : package/lib/lib/release/ti.uia.events/UIAThreadCtx.srm4
UIAUserCtx.orm4,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.orm4
UIAUserCtx.srm4,copy : package/lib/lib/release/ti.uia.events/UIAUserCtx.srm4

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_uia_events
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_uia_events.tar.dep
endif
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: package/package.bld.xml
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: package/build.cfg
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: package.bld
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: lib/release/ti.uia.events.aem3
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: package/package_ti.uia.events.c
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: UIAAppCtx.c
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: UIAChanCtx.c
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: UIAFrameCtx.c
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: UIAThreadCtx.c
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: UIAUserCtx.c
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: lib/release/ti.uia.events.aem4
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: lib/release/ti.uia.events.am3g
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: lib/release/ti.uia.events.am4g
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: lib/release/ti.uia.events.arm3
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: lib/release/ti.uia.events.arm4
package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_uia_events.tar: package/rel/ti_uia_events.xdc.inc package/rel/ti_uia_events/ti/uia/events/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_uia_events.xdc.inc,package/rel/ti_uia_events.tar.dep)


release release,ti_uia_events: all ti_uia_events.tar
clean:: .clean
	-$(RM) ti_uia_events.tar
	-$(RM) package/rel/ti_uia_events.xdc.inc
	-$(RM) package/rel/ti_uia_events.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.uia.events))
    $(shell $(MKDIR) package/lib/lib/release/ti.uia.events)
endif
ifeq (,$(wildcard package/lib/lib/release/ti.uia.events/package))
    $(shell $(MKDIR) package/lib/lib/release/ti.uia.events/package)
endif
endif
clean::
	-$(RMDIR) package


