/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A71
 */

#ifndef ti_uia_family_dm_TimestampDM816XTimer__INTERNAL__
#define ti_uia_family_dm_TimestampDM816XTimer__INTERNAL__

#ifndef ti_uia_family_dm_TimestampDM816XTimer__internalaccess
#define ti_uia_family_dm_TimestampDM816XTimer__internalaccess
#endif

#include <ti/uia/family/dm/TimestampDM816XTimer.h>

#undef xdc_FILE__
#ifndef xdc_FILE
#define xdc_FILE__ NULL
#else
#define xdc_FILE__ xdc_FILE
#endif

/* get32 */
#undef ti_uia_family_dm_TimestampDM816XTimer_get32
#define ti_uia_family_dm_TimestampDM816XTimer_get32 ti_uia_family_dm_TimestampDM816XTimer_get32__E

/* get64 */
#undef ti_uia_family_dm_TimestampDM816XTimer_get64
#define ti_uia_family_dm_TimestampDM816XTimer_get64 ti_uia_family_dm_TimestampDM816XTimer_get64__E

/* getFreq */
#undef ti_uia_family_dm_TimestampDM816XTimer_getFreq
#define ti_uia_family_dm_TimestampDM816XTimer_getFreq ti_uia_family_dm_TimestampDM816XTimer_getFreq__E

/* setMSW */
#undef ti_uia_family_dm_TimestampDM816XTimer_setMSW
#define ti_uia_family_dm_TimestampDM816XTimer_setMSW ti_uia_family_dm_TimestampDM816XTimer_setMSW__E

/* start */
#define TimestampDM816XTimer_start ti_uia_family_dm_TimestampDM816XTimer_start__I

/* stop */
#define TimestampDM816XTimer_stop ti_uia_family_dm_TimestampDM816XTimer_stop__I

/* Module_startup */
#undef ti_uia_family_dm_TimestampDM816XTimer_Module_startup
#define ti_uia_family_dm_TimestampDM816XTimer_Module_startup ti_uia_family_dm_TimestampDM816XTimer_Module_startup__E

/* Instance_init */
#undef ti_uia_family_dm_TimestampDM816XTimer_Instance_init
#define ti_uia_family_dm_TimestampDM816XTimer_Instance_init ti_uia_family_dm_TimestampDM816XTimer_Instance_init__E

/* Instance_finalize */
#undef ti_uia_family_dm_TimestampDM816XTimer_Instance_finalize
#define ti_uia_family_dm_TimestampDM816XTimer_Instance_finalize ti_uia_family_dm_TimestampDM816XTimer_Instance_finalize__E

/* module */
#define TimestampDM816XTimer_module ((ti_uia_family_dm_TimestampDM816XTimer_Module_State *)(xdc__MODOBJADDR__(ti_uia_family_dm_TimestampDM816XTimer_Module__state__V)))
#if !defined(__cplusplus) || !defined(ti_uia_family_dm_TimestampDM816XTimer__cplusplus)
#define module ((ti_uia_family_dm_TimestampDM816XTimer_Module_State *)(xdc__MODOBJADDR__(ti_uia_family_dm_TimestampDM816XTimer_Module__state__V)))
#endif
/* per-module runtime symbols */
#undef Module__MID
#define Module__MID ti_uia_family_dm_TimestampDM816XTimer_Module__id__C
#undef Module__DGSINCL
#define Module__DGSINCL ti_uia_family_dm_TimestampDM816XTimer_Module__diagsIncluded__C
#undef Module__DGSENAB
#define Module__DGSENAB ti_uia_family_dm_TimestampDM816XTimer_Module__diagsEnabled__C
#undef Module__DGSMASK
#define Module__DGSMASK ti_uia_family_dm_TimestampDM816XTimer_Module__diagsMask__C
#undef Module__LOGDEF
#define Module__LOGDEF ti_uia_family_dm_TimestampDM816XTimer_Module__loggerDefined__C
#undef Module__LOGOBJ
#define Module__LOGOBJ ti_uia_family_dm_TimestampDM816XTimer_Module__loggerObj__C
#undef Module__LOGFXN0
#define Module__LOGFXN0 ti_uia_family_dm_TimestampDM816XTimer_Module__loggerFxn0__C
#undef Module__LOGFXN1
#define Module__LOGFXN1 ti_uia_family_dm_TimestampDM816XTimer_Module__loggerFxn1__C
#undef Module__LOGFXN2
#define Module__LOGFXN2 ti_uia_family_dm_TimestampDM816XTimer_Module__loggerFxn2__C
#undef Module__LOGFXN4
#define Module__LOGFXN4 ti_uia_family_dm_TimestampDM816XTimer_Module__loggerFxn4__C
#undef Module__LOGFXN8
#define Module__LOGFXN8 ti_uia_family_dm_TimestampDM816XTimer_Module__loggerFxn8__C
#undef Module__G_OBJ
#define Module__G_OBJ ti_uia_family_dm_TimestampDM816XTimer_Module__gateObj__C
#undef Module__G_PRMS
#define Module__G_PRMS ti_uia_family_dm_TimestampDM816XTimer_Module__gatePrms__C
#undef Module__GP_create
#define Module__GP_create ti_uia_family_dm_TimestampDM816XTimer_Module_GateProxy_create
#undef Module__GP_delete
#define Module__GP_delete ti_uia_family_dm_TimestampDM816XTimer_Module_GateProxy_delete
#undef Module__GP_enter
#define Module__GP_enter ti_uia_family_dm_TimestampDM816XTimer_Module_GateProxy_enter
#undef Module__GP_leave
#define Module__GP_leave ti_uia_family_dm_TimestampDM816XTimer_Module_GateProxy_leave
#undef Module__GP_query
#define Module__GP_query ti_uia_family_dm_TimestampDM816XTimer_Module_GateProxy_query


#endif /* ti_uia_family_dm_TimestampDM816XTimer__INTERNAL____ */
