/******************************************************************************
*  Filename:       prop_cmd_field.h
*  Revised:        $ $
*  Revision:       $ $
*
*  Description:    CC13xx API for Proprietary mode commands
*
*  Copyright (C) 2015 Texas Instruments Incorporated - http://www.ti.com/
*
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
******************************************************************************/

#ifndef __PROP_CMD_FIELD_H
#define __PROP_CMD_FIELD_H

#include <stdint.h>
#include "mailbox.h"
#include "common_cmd.h"

#define _POSITION_carrierSense_csConf                           0
#define _TYPE_carrierSense_csConf                               uint8_t
#define _BITPOS_carrierSense_csConf_bEnaRssi                    0
#define _NBITS_carrierSense_csConf_bEnaRssi                     1
#define _BITPOS_carrierSense_csConf_bEnaCorr                    1
#define _NBITS_carrierSense_csConf_bEnaCorr                     1
#define _BITPOS_carrierSense_csConf_operation                   2
#define _NBITS_carrierSense_csConf_operation                    1
#define _BITPOS_carrierSense_csConf_busyOp                      3
#define _NBITS_carrierSense_csConf_busyOp                       1
#define _BITPOS_carrierSense_csConf_idleOp                      4
#define _NBITS_carrierSense_csConf_idleOp                       1
#define _BITPOS_carrierSense_csConf_timeoutRes                  5
#define _NBITS_carrierSense_csConf_timeoutRes                   1
#define _POSITION_carrierSense_rssiThr                          1
#define _TYPE_carrierSense_rssiThr                              int8_t
#define _POSITION_carrierSense_numRssiIdle                      2
#define _TYPE_carrierSense_numRssiIdle                          uint8_t
#define _POSITION_carrierSense_numRssiBusy                      3
#define _TYPE_carrierSense_numRssiBusy                          uint8_t
#define _POSITION_carrierSense_corrPeriod                       4
#define _TYPE_carrierSense_corrPeriod                           uint16_t
#define _POSITION_carrierSense_corrConfig                       6
#define _TYPE_carrierSense_corrConfig                           uint8_t
#define _BITPOS_carrierSense_corrConfig_numCorrInv              0
#define _NBITS_carrierSense_corrConfig_numCorrInv               4
#define _BITPOS_carrierSense_corrConfig_numCorrBusy             4
#define _NBITS_carrierSense_corrConfig_numCorrBusy              4
#define _POSITION_carrierSense_csEndTrigger                     7
#define _TYPE_carrierSense_csEndTrigger                         uint8_t
#define _BITPOS_carrierSense_csEndTrigger_triggerType           0
#define _NBITS_carrierSense_csEndTrigger_triggerType            4
#define _BITPOS_carrierSense_csEndTrigger_bEnaCmd               4
#define _NBITS_carrierSense_csEndTrigger_bEnaCmd                1
#define _BITPOS_carrierSense_csEndTrigger_triggerNo             5
#define _NBITS_carrierSense_csEndTrigger_triggerNo              2
#define _BITPOS_carrierSense_csEndTrigger_pastTrig              7
#define _NBITS_carrierSense_csEndTrigger_pastTrig               1
#define _POSITION_carrierSense_csEndTime                        8
#define _TYPE_carrierSense_csEndTime                            ratmr_t
#define _SIZEOF_carrierSense                                    12

#define _POSITION_CMD_PROP_TX_commandNo                         0
#define _TYPE_CMD_PROP_TX_commandNo                             uint16_t
#define _POSITION_CMD_PROP_TX_status                            2
#define _TYPE_CMD_PROP_TX_status                                uint16_t
#define _POSITION_CMD_PROP_TX_pNextOp                           4
#define _TYPE_CMD_PROP_TX_pNextOp                               uint8_t*
#define _POSITION_CMD_PROP_TX_startTime                         8
#define _TYPE_CMD_PROP_TX_startTime                             ratmr_t
#define _POSITION_CMD_PROP_TX_startTrigger                      12
#define _TYPE_CMD_PROP_TX_startTrigger                          uint8_t
#define _BITPOS_CMD_PROP_TX_startTrigger_triggerType            0
#define _NBITS_CMD_PROP_TX_startTrigger_triggerType             4
#define _BITPOS_CMD_PROP_TX_startTrigger_bEnaCmd                4
#define _NBITS_CMD_PROP_TX_startTrigger_bEnaCmd                 1
#define _BITPOS_CMD_PROP_TX_startTrigger_triggerNo              5
#define _NBITS_CMD_PROP_TX_startTrigger_triggerNo               2
#define _BITPOS_CMD_PROP_TX_startTrigger_pastTrig               7
#define _NBITS_CMD_PROP_TX_startTrigger_pastTrig                1
#define _POSITION_CMD_PROP_TX_condition                         13
#define _TYPE_CMD_PROP_TX_condition                             uint8_t
#define _BITPOS_CMD_PROP_TX_condition_rule                      0
#define _NBITS_CMD_PROP_TX_condition_rule                       4
#define _BITPOS_CMD_PROP_TX_condition_nSkip                     4
#define _NBITS_CMD_PROP_TX_condition_nSkip                      4
#define _POSITION_CMD_PROP_TX_pktConf                           14
#define _TYPE_CMD_PROP_TX_pktConf                               uint8_t
#define _BITPOS_CMD_PROP_TX_pktConf_bFsOff                      0
#define _NBITS_CMD_PROP_TX_pktConf_bFsOff                       1
#define _BITPOS_CMD_PROP_TX_pktConf_bUseCrc                     3
#define _NBITS_CMD_PROP_TX_pktConf_bUseCrc                      1
#define _BITPOS_CMD_PROP_TX_pktConf_bVarLen                     4
#define _NBITS_CMD_PROP_TX_pktConf_bVarLen                      1
#define _POSITION_CMD_PROP_TX_pktLen                            15
#define _TYPE_CMD_PROP_TX_pktLen                                uint8_t
#define _POSITION_CMD_PROP_TX_syncWord                          16
#define _TYPE_CMD_PROP_TX_syncWord                              uint32_t
#define _POSITION_CMD_PROP_TX_pPkt                              20
#define _TYPE_CMD_PROP_TX_pPkt                                  uint8_t*
#define _SIZEOF_CMD_PROP_TX                                     24

#define _POSITION_CMD_PROP_RX_commandNo                         0
#define _TYPE_CMD_PROP_RX_commandNo                             uint16_t
#define _POSITION_CMD_PROP_RX_status                            2
#define _TYPE_CMD_PROP_RX_status                                uint16_t
#define _POSITION_CMD_PROP_RX_pNextOp                           4
#define _TYPE_CMD_PROP_RX_pNextOp                               uint8_t*
#define _POSITION_CMD_PROP_RX_startTime                         8
#define _TYPE_CMD_PROP_RX_startTime                             ratmr_t
#define _POSITION_CMD_PROP_RX_startTrigger                      12
#define _TYPE_CMD_PROP_RX_startTrigger                          uint8_t
#define _BITPOS_CMD_PROP_RX_startTrigger_triggerType            0
#define _NBITS_CMD_PROP_RX_startTrigger_triggerType             4
#define _BITPOS_CMD_PROP_RX_startTrigger_bEnaCmd                4
#define _NBITS_CMD_PROP_RX_startTrigger_bEnaCmd                 1
#define _BITPOS_CMD_PROP_RX_startTrigger_triggerNo              5
#define _NBITS_CMD_PROP_RX_startTrigger_triggerNo               2
#define _BITPOS_CMD_PROP_RX_startTrigger_pastTrig               7
#define _NBITS_CMD_PROP_RX_startTrigger_pastTrig                1
#define _POSITION_CMD_PROP_RX_condition                         13
#define _TYPE_CMD_PROP_RX_condition                             uint8_t
#define _BITPOS_CMD_PROP_RX_condition_rule                      0
#define _NBITS_CMD_PROP_RX_condition_rule                       4
#define _BITPOS_CMD_PROP_RX_condition_nSkip                     4
#define _NBITS_CMD_PROP_RX_condition_nSkip                      4
#define _POSITION_CMD_PROP_RX_pktConf                           14
#define _TYPE_CMD_PROP_RX_pktConf                               uint8_t
#define _BITPOS_CMD_PROP_RX_pktConf_bFsOff                      0
#define _NBITS_CMD_PROP_RX_pktConf_bFsOff                       1
#define _BITPOS_CMD_PROP_RX_pktConf_bRepeatOk                   1
#define _NBITS_CMD_PROP_RX_pktConf_bRepeatOk                    1
#define _BITPOS_CMD_PROP_RX_pktConf_bRepeatNok                  2
#define _NBITS_CMD_PROP_RX_pktConf_bRepeatNok                   1
#define _BITPOS_CMD_PROP_RX_pktConf_bUseCrc                     3
#define _NBITS_CMD_PROP_RX_pktConf_bUseCrc                      1
#define _BITPOS_CMD_PROP_RX_pktConf_bVarLen                     4
#define _NBITS_CMD_PROP_RX_pktConf_bVarLen                      1
#define _BITPOS_CMD_PROP_RX_pktConf_bChkAddress                 5
#define _NBITS_CMD_PROP_RX_pktConf_bChkAddress                  1
#define _BITPOS_CMD_PROP_RX_pktConf_endType                     6
#define _NBITS_CMD_PROP_RX_pktConf_endType                      1
#define _BITPOS_CMD_PROP_RX_pktConf_filterOp                    7
#define _NBITS_CMD_PROP_RX_pktConf_filterOp                     1
#define _POSITION_CMD_PROP_RX_rxConf                            15
#define _TYPE_CMD_PROP_RX_rxConf                                uint8_t
#define _BITPOS_CMD_PROP_RX_rxConf_bAutoFlushIgnored            0
#define _NBITS_CMD_PROP_RX_rxConf_bAutoFlushIgnored             1
#define _BITPOS_CMD_PROP_RX_rxConf_bAutoFlushCrcErr             1
#define _NBITS_CMD_PROP_RX_rxConf_bAutoFlushCrcErr              1
#define _BITPOS_CMD_PROP_RX_rxConf_bIncludeHdr                  3
#define _NBITS_CMD_PROP_RX_rxConf_bIncludeHdr                   1
#define _BITPOS_CMD_PROP_RX_rxConf_bIncludeCrc                  4
#define _NBITS_CMD_PROP_RX_rxConf_bIncludeCrc                   1
#define _BITPOS_CMD_PROP_RX_rxConf_bAppendRssi                  5
#define _NBITS_CMD_PROP_RX_rxConf_bAppendRssi                   1
#define _BITPOS_CMD_PROP_RX_rxConf_bAppendTimestamp             6
#define _NBITS_CMD_PROP_RX_rxConf_bAppendTimestamp              1
#define _BITPOS_CMD_PROP_RX_rxConf_bAppendStatus                7
#define _NBITS_CMD_PROP_RX_rxConf_bAppendStatus                 1
#define _POSITION_CMD_PROP_RX_syncWord                          16
#define _TYPE_CMD_PROP_RX_syncWord                              uint32_t
#define _POSITION_CMD_PROP_RX_maxPktLen                         20
#define _TYPE_CMD_PROP_RX_maxPktLen                             uint8_t
#define _POSITION_CMD_PROP_RX_address0                          21
#define _TYPE_CMD_PROP_RX_address0                              uint8_t
#define _POSITION_CMD_PROP_RX_address1                          22
#define _TYPE_CMD_PROP_RX_address1                              uint8_t
#define _POSITION_CMD_PROP_RX_endTrigger                        23
#define _TYPE_CMD_PROP_RX_endTrigger                            uint8_t
#define _BITPOS_CMD_PROP_RX_endTrigger_triggerType              0
#define _NBITS_CMD_PROP_RX_endTrigger_triggerType               4
#define _BITPOS_CMD_PROP_RX_endTrigger_bEnaCmd                  4
#define _NBITS_CMD_PROP_RX_endTrigger_bEnaCmd                   1
#define _BITPOS_CMD_PROP_RX_endTrigger_triggerNo                5
#define _NBITS_CMD_PROP_RX_endTrigger_triggerNo                 2
#define _BITPOS_CMD_PROP_RX_endTrigger_pastTrig                 7
#define _NBITS_CMD_PROP_RX_endTrigger_pastTrig                  1
#define _POSITION_CMD_PROP_RX_endTime                           24
#define _TYPE_CMD_PROP_RX_endTime                               ratmr_t
#define _POSITION_CMD_PROP_RX_pQueue                            28
#define _TYPE_CMD_PROP_RX_pQueue                                dataQueue_t*
#define _POSITION_CMD_PROP_RX_pOutput                           32
#define _TYPE_CMD_PROP_RX_pOutput                               uint8_t*
#define _SIZEOF_CMD_PROP_RX                                     36

#define _POSITION_CMD_PROP_TX_ADV_commandNo                     0
#define _TYPE_CMD_PROP_TX_ADV_commandNo                         uint16_t
#define _POSITION_CMD_PROP_TX_ADV_status                        2
#define _TYPE_CMD_PROP_TX_ADV_status                            uint16_t
#define _POSITION_CMD_PROP_TX_ADV_pNextOp                       4
#define _TYPE_CMD_PROP_TX_ADV_pNextOp                           uint8_t*
#define _POSITION_CMD_PROP_TX_ADV_startTime                     8
#define _TYPE_CMD_PROP_TX_ADV_startTime                         ratmr_t
#define _POSITION_CMD_PROP_TX_ADV_startTrigger                  12
#define _TYPE_CMD_PROP_TX_ADV_startTrigger                      uint8_t
#define _BITPOS_CMD_PROP_TX_ADV_startTrigger_triggerType        0
#define _NBITS_CMD_PROP_TX_ADV_startTrigger_triggerType         4
#define _BITPOS_CMD_PROP_TX_ADV_startTrigger_bEnaCmd            4
#define _NBITS_CMD_PROP_TX_ADV_startTrigger_bEnaCmd             1
#define _BITPOS_CMD_PROP_TX_ADV_startTrigger_triggerNo          5
#define _NBITS_CMD_PROP_TX_ADV_startTrigger_triggerNo           2
#define _BITPOS_CMD_PROP_TX_ADV_startTrigger_pastTrig           7
#define _NBITS_CMD_PROP_TX_ADV_startTrigger_pastTrig            1
#define _POSITION_CMD_PROP_TX_ADV_condition                     13
#define _TYPE_CMD_PROP_TX_ADV_condition                         uint8_t
#define _BITPOS_CMD_PROP_TX_ADV_condition_rule                  0
#define _NBITS_CMD_PROP_TX_ADV_condition_rule                   4
#define _BITPOS_CMD_PROP_TX_ADV_condition_nSkip                 4
#define _NBITS_CMD_PROP_TX_ADV_condition_nSkip                  4
#define _POSITION_CMD_PROP_TX_ADV_pktConf                       14
#define _TYPE_CMD_PROP_TX_ADV_pktConf                           uint8_t
#define _BITPOS_CMD_PROP_TX_ADV_pktConf_bFsOff                  0
#define _NBITS_CMD_PROP_TX_ADV_pktConf_bFsOff                   1
#define _BITPOS_CMD_PROP_TX_ADV_pktConf_bUseCrc                 3
#define _NBITS_CMD_PROP_TX_ADV_pktConf_bUseCrc                  1
#define _BITPOS_CMD_PROP_TX_ADV_pktConf_bCrcIncSw               4
#define _NBITS_CMD_PROP_TX_ADV_pktConf_bCrcIncSw                1
#define _BITPOS_CMD_PROP_TX_ADV_pktConf_bCrcIncHdr              5
#define _NBITS_CMD_PROP_TX_ADV_pktConf_bCrcIncHdr               1
#define _POSITION_CMD_PROP_TX_ADV_numHdrBits                    15
#define _TYPE_CMD_PROP_TX_ADV_numHdrBits                        uint8_t
#define _POSITION_CMD_PROP_TX_ADV_pktLen                        16
#define _TYPE_CMD_PROP_TX_ADV_pktLen                            uint16_t
#define _POSITION_CMD_PROP_TX_ADV_startConf                     18
#define _TYPE_CMD_PROP_TX_ADV_startConf                         uint8_t
#define _BITPOS_CMD_PROP_TX_ADV_startConf_bExtTxTrig            0
#define _NBITS_CMD_PROP_TX_ADV_startConf_bExtTxTrig             1
#define _BITPOS_CMD_PROP_TX_ADV_startConf_inputMode             1
#define _NBITS_CMD_PROP_TX_ADV_startConf_inputMode              2
#define _BITPOS_CMD_PROP_TX_ADV_startConf_source                3
#define _NBITS_CMD_PROP_TX_ADV_startConf_source                 5
#define _POSITION_CMD_PROP_TX_ADV_preTrigger                    19
#define _TYPE_CMD_PROP_TX_ADV_preTrigger                        uint8_t
#define _BITPOS_CMD_PROP_TX_ADV_preTrigger_triggerType          0
#define _NBITS_CMD_PROP_TX_ADV_preTrigger_triggerType           4
#define _BITPOS_CMD_PROP_TX_ADV_preTrigger_bEnaCmd              4
#define _NBITS_CMD_PROP_TX_ADV_preTrigger_bEnaCmd               1
#define _BITPOS_CMD_PROP_TX_ADV_preTrigger_triggerNo            5
#define _NBITS_CMD_PROP_TX_ADV_preTrigger_triggerNo             2
#define _BITPOS_CMD_PROP_TX_ADV_preTrigger_pastTrig             7
#define _NBITS_CMD_PROP_TX_ADV_preTrigger_pastTrig              1
#define _POSITION_CMD_PROP_TX_ADV_preTime                       20
#define _TYPE_CMD_PROP_TX_ADV_preTime                           ratmr_t
#define _POSITION_CMD_PROP_TX_ADV_syncWord                      24
#define _TYPE_CMD_PROP_TX_ADV_syncWord                          uint32_t
#define _POSITION_CMD_PROP_TX_ADV_pPkt                          28
#define _TYPE_CMD_PROP_TX_ADV_pPkt                              uint8_t*
#define _SIZEOF_CMD_PROP_TX_ADV                                 32

#define _POSITION_CMD_PROP_RX_ADV_commandNo                     0
#define _TYPE_CMD_PROP_RX_ADV_commandNo                         uint16_t
#define _POSITION_CMD_PROP_RX_ADV_status                        2
#define _TYPE_CMD_PROP_RX_ADV_status                            uint16_t
#define _POSITION_CMD_PROP_RX_ADV_pNextOp                       4
#define _TYPE_CMD_PROP_RX_ADV_pNextOp                           uint8_t*
#define _POSITION_CMD_PROP_RX_ADV_startTime                     8
#define _TYPE_CMD_PROP_RX_ADV_startTime                         ratmr_t
#define _POSITION_CMD_PROP_RX_ADV_startTrigger                  12
#define _TYPE_CMD_PROP_RX_ADV_startTrigger                      uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_startTrigger_triggerType        0
#define _NBITS_CMD_PROP_RX_ADV_startTrigger_triggerType         4
#define _BITPOS_CMD_PROP_RX_ADV_startTrigger_bEnaCmd            4
#define _NBITS_CMD_PROP_RX_ADV_startTrigger_bEnaCmd             1
#define _BITPOS_CMD_PROP_RX_ADV_startTrigger_triggerNo          5
#define _NBITS_CMD_PROP_RX_ADV_startTrigger_triggerNo           2
#define _BITPOS_CMD_PROP_RX_ADV_startTrigger_pastTrig           7
#define _NBITS_CMD_PROP_RX_ADV_startTrigger_pastTrig            1
#define _POSITION_CMD_PROP_RX_ADV_condition                     13
#define _TYPE_CMD_PROP_RX_ADV_condition                         uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_condition_rule                  0
#define _NBITS_CMD_PROP_RX_ADV_condition_rule                   4
#define _BITPOS_CMD_PROP_RX_ADV_condition_nSkip                 4
#define _NBITS_CMD_PROP_RX_ADV_condition_nSkip                  4
#define _POSITION_CMD_PROP_RX_ADV_pktConf                       14
#define _TYPE_CMD_PROP_RX_ADV_pktConf                           uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_bFsOff                  0
#define _NBITS_CMD_PROP_RX_ADV_pktConf_bFsOff                   1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_bRepeatOk               1
#define _NBITS_CMD_PROP_RX_ADV_pktConf_bRepeatOk                1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_bRepeatNok              2
#define _NBITS_CMD_PROP_RX_ADV_pktConf_bRepeatNok               1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_bUseCrc                 3
#define _NBITS_CMD_PROP_RX_ADV_pktConf_bUseCrc                  1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_bCrcIncSw               4
#define _NBITS_CMD_PROP_RX_ADV_pktConf_bCrcIncSw                1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_bCrcIncHdr              5
#define _NBITS_CMD_PROP_RX_ADV_pktConf_bCrcIncHdr               1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_endType                 6
#define _NBITS_CMD_PROP_RX_ADV_pktConf_endType                  1
#define _BITPOS_CMD_PROP_RX_ADV_pktConf_filterOp                7
#define _NBITS_CMD_PROP_RX_ADV_pktConf_filterOp                 1
#define _POSITION_CMD_PROP_RX_ADV_rxConf                        15
#define _TYPE_CMD_PROP_RX_ADV_rxConf                            uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bAutoFlushIgnored        0
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bAutoFlushIgnored         1
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bAutoFlushCrcErr         1
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bAutoFlushCrcErr          1
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bIncludeHdr              3
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bIncludeHdr               1
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bIncludeCrc              4
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bIncludeCrc               1
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bAppendRssi              5
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bAppendRssi               1
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bAppendTimestamp         6
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bAppendTimestamp          1
#define _BITPOS_CMD_PROP_RX_ADV_rxConf_bAppendStatus            7
#define _NBITS_CMD_PROP_RX_ADV_rxConf_bAppendStatus             1
#define _POSITION_CMD_PROP_RX_ADV_syncWord0                     16
#define _TYPE_CMD_PROP_RX_ADV_syncWord0                         uint32_t
#define _POSITION_CMD_PROP_RX_ADV_syncWord1                     20
#define _TYPE_CMD_PROP_RX_ADV_syncWord1                         uint32_t
#define _POSITION_CMD_PROP_RX_ADV_maxPktLen                     24
#define _TYPE_CMD_PROP_RX_ADV_maxPktLen                         uint16_t
#define _POSITION_CMD_PROP_RX_ADV_hdrConf                       26
#define _TYPE_CMD_PROP_RX_ADV_hdrConf                           uint16_t
#define _BITPOS_CMD_PROP_RX_ADV_hdrConf_numHdrBits              0
#define _NBITS_CMD_PROP_RX_ADV_hdrConf_numHdrBits               6
#define _BITPOS_CMD_PROP_RX_ADV_hdrConf_lenPos                  6
#define _NBITS_CMD_PROP_RX_ADV_hdrConf_lenPos                   5
#define _BITPOS_CMD_PROP_RX_ADV_hdrConf_numLenBits              11
#define _NBITS_CMD_PROP_RX_ADV_hdrConf_numLenBits               5
#define _POSITION_CMD_PROP_RX_ADV_addrConf                      28
#define _TYPE_CMD_PROP_RX_ADV_addrConf                          uint16_t
#define _BITPOS_CMD_PROP_RX_ADV_addrConf_addrType               0
#define _NBITS_CMD_PROP_RX_ADV_addrConf_addrType                1
#define _BITPOS_CMD_PROP_RX_ADV_addrConf_addrSize               1
#define _NBITS_CMD_PROP_RX_ADV_addrConf_addrSize                5
#define _BITPOS_CMD_PROP_RX_ADV_addrConf_addrPos                6
#define _NBITS_CMD_PROP_RX_ADV_addrConf_addrPos                 5
#define _BITPOS_CMD_PROP_RX_ADV_addrConf_numAddr                11
#define _NBITS_CMD_PROP_RX_ADV_addrConf_numAddr                 5
#define _POSITION_CMD_PROP_RX_ADV_lenOffset                     30
#define _TYPE_CMD_PROP_RX_ADV_lenOffset                         int8_t
#define _POSITION_CMD_PROP_RX_ADV_endTrigger                    31
#define _TYPE_CMD_PROP_RX_ADV_endTrigger                        uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_endTrigger_triggerType          0
#define _NBITS_CMD_PROP_RX_ADV_endTrigger_triggerType           4
#define _BITPOS_CMD_PROP_RX_ADV_endTrigger_bEnaCmd              4
#define _NBITS_CMD_PROP_RX_ADV_endTrigger_bEnaCmd               1
#define _BITPOS_CMD_PROP_RX_ADV_endTrigger_triggerNo            5
#define _NBITS_CMD_PROP_RX_ADV_endTrigger_triggerNo             2
#define _BITPOS_CMD_PROP_RX_ADV_endTrigger_pastTrig             7
#define _NBITS_CMD_PROP_RX_ADV_endTrigger_pastTrig              1
#define _POSITION_CMD_PROP_RX_ADV_endTime                       32
#define _TYPE_CMD_PROP_RX_ADV_endTime                           ratmr_t
#define _POSITION_CMD_PROP_RX_ADV_pAddr                         36
#define _TYPE_CMD_PROP_RX_ADV_pAddr                             uint8_t*
#define _POSITION_CMD_PROP_RX_ADV_pQueue                        40
#define _TYPE_CMD_PROP_RX_ADV_pQueue                            dataQueue_t*
#define _POSITION_CMD_PROP_RX_ADV_pOutput                       44
#define _TYPE_CMD_PROP_RX_ADV_pOutput                           uint8_t*
#define _SIZEOF_CMD_PROP_RX_ADV                                 48

#define _POSITION_CMD_PROP_CS_commandNo                         0
#define _TYPE_CMD_PROP_CS_commandNo                             uint16_t
#define _POSITION_CMD_PROP_CS_status                            2
#define _TYPE_CMD_PROP_CS_status                                uint16_t
#define _POSITION_CMD_PROP_CS_pNextOp                           4
#define _TYPE_CMD_PROP_CS_pNextOp                               uint8_t*
#define _POSITION_CMD_PROP_CS_startTime                         8
#define _TYPE_CMD_PROP_CS_startTime                             ratmr_t
#define _POSITION_CMD_PROP_CS_startTrigger                      12
#define _TYPE_CMD_PROP_CS_startTrigger                          uint8_t
#define _BITPOS_CMD_PROP_CS_startTrigger_triggerType            0
#define _NBITS_CMD_PROP_CS_startTrigger_triggerType             4
#define _BITPOS_CMD_PROP_CS_startTrigger_bEnaCmd                4
#define _NBITS_CMD_PROP_CS_startTrigger_bEnaCmd                 1
#define _BITPOS_CMD_PROP_CS_startTrigger_triggerNo              5
#define _NBITS_CMD_PROP_CS_startTrigger_triggerNo               2
#define _BITPOS_CMD_PROP_CS_startTrigger_pastTrig               7
#define _NBITS_CMD_PROP_CS_startTrigger_pastTrig                1
#define _POSITION_CMD_PROP_CS_condition                         13
#define _TYPE_CMD_PROP_CS_condition                             uint8_t
#define _BITPOS_CMD_PROP_CS_condition_rule                      0
#define _NBITS_CMD_PROP_CS_condition_rule                       4
#define _BITPOS_CMD_PROP_CS_condition_nSkip                     4
#define _NBITS_CMD_PROP_CS_condition_nSkip                      4
#define _POSITION_CMD_PROP_CS_csFsConf                          14
#define _TYPE_CMD_PROP_CS_csFsConf                              uint8_t
#define _BITPOS_CMD_PROP_CS_csFsConf_bFsOffIdle                 0
#define _NBITS_CMD_PROP_CS_csFsConf_bFsOffIdle                  1
#define _BITPOS_CMD_PROP_CS_csFsConf_bFsOffBusy                 1
#define _NBITS_CMD_PROP_CS_csFsConf_bFsOffBusy                  1
#define _POSITION_CMD_PROP_CS_csConf                            16
#define _TYPE_CMD_PROP_CS_csConf                                uint8_t
#define _BITPOS_CMD_PROP_CS_csConf_bEnaRssi                     0
#define _NBITS_CMD_PROP_CS_csConf_bEnaRssi                      1
#define _BITPOS_CMD_PROP_CS_csConf_bEnaCorr                     1
#define _NBITS_CMD_PROP_CS_csConf_bEnaCorr                      1
#define _BITPOS_CMD_PROP_CS_csConf_operation                    2
#define _NBITS_CMD_PROP_CS_csConf_operation                     1
#define _BITPOS_CMD_PROP_CS_csConf_busyOp                       3
#define _NBITS_CMD_PROP_CS_csConf_busyOp                        1
#define _BITPOS_CMD_PROP_CS_csConf_idleOp                       4
#define _NBITS_CMD_PROP_CS_csConf_idleOp                        1
#define _BITPOS_CMD_PROP_CS_csConf_timeoutRes                   5
#define _NBITS_CMD_PROP_CS_csConf_timeoutRes                    1
#define _POSITION_CMD_PROP_CS_rssiThr                           17
#define _TYPE_CMD_PROP_CS_rssiThr                               int8_t
#define _POSITION_CMD_PROP_CS_numRssiIdle                       18
#define _TYPE_CMD_PROP_CS_numRssiIdle                           uint8_t
#define _POSITION_CMD_PROP_CS_numRssiBusy                       19
#define _TYPE_CMD_PROP_CS_numRssiBusy                           uint8_t
#define _POSITION_CMD_PROP_CS_corrPeriod                        20
#define _TYPE_CMD_PROP_CS_corrPeriod                            uint16_t
#define _POSITION_CMD_PROP_CS_corrConfig                        22
#define _TYPE_CMD_PROP_CS_corrConfig                            uint8_t
#define _BITPOS_CMD_PROP_CS_corrConfig_numCorrInv               0
#define _NBITS_CMD_PROP_CS_corrConfig_numCorrInv                4
#define _BITPOS_CMD_PROP_CS_corrConfig_numCorrBusy              4
#define _NBITS_CMD_PROP_CS_corrConfig_numCorrBusy               4
#define _POSITION_CMD_PROP_CS_csEndTrigger                      23
#define _TYPE_CMD_PROP_CS_csEndTrigger                          uint8_t
#define _BITPOS_CMD_PROP_CS_csEndTrigger_triggerType            0
#define _NBITS_CMD_PROP_CS_csEndTrigger_triggerType             4
#define _BITPOS_CMD_PROP_CS_csEndTrigger_bEnaCmd                4
#define _NBITS_CMD_PROP_CS_csEndTrigger_bEnaCmd                 1
#define _BITPOS_CMD_PROP_CS_csEndTrigger_triggerNo              5
#define _NBITS_CMD_PROP_CS_csEndTrigger_triggerNo               2
#define _BITPOS_CMD_PROP_CS_csEndTrigger_pastTrig               7
#define _NBITS_CMD_PROP_CS_csEndTrigger_pastTrig                1
#define _POSITION_CMD_PROP_CS_csEndTime                         24
#define _TYPE_CMD_PROP_CS_csEndTime                             ratmr_t
#define _POSITION_CMD_PROP_CS_carrierSense                      16
#define _TYPE_CMD_PROP_CS_carrierSense                          uint8_t
#define _SIZEOF_CMD_PROP_CS                                     28

#define _POSITION_CMD_PROP_RADIO_SETUP_commandNo                0
#define _TYPE_CMD_PROP_RADIO_SETUP_commandNo                    uint16_t
#define _POSITION_CMD_PROP_RADIO_SETUP_status                   2
#define _TYPE_CMD_PROP_RADIO_SETUP_status                       uint16_t
#define _POSITION_CMD_PROP_RADIO_SETUP_pNextOp                  4
#define _TYPE_CMD_PROP_RADIO_SETUP_pNextOp                      uint8_t*
#define _POSITION_CMD_PROP_RADIO_SETUP_startTime                8
#define _TYPE_CMD_PROP_RADIO_SETUP_startTime                    ratmr_t
#define _POSITION_CMD_PROP_RADIO_SETUP_startTrigger             12
#define _TYPE_CMD_PROP_RADIO_SETUP_startTrigger                 uint8_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_startTrigger_triggerType   0
#define _NBITS_CMD_PROP_RADIO_SETUP_startTrigger_triggerType    4
#define _BITPOS_CMD_PROP_RADIO_SETUP_startTrigger_bEnaCmd       4
#define _NBITS_CMD_PROP_RADIO_SETUP_startTrigger_bEnaCmd        1
#define _BITPOS_CMD_PROP_RADIO_SETUP_startTrigger_triggerNo     5
#define _NBITS_CMD_PROP_RADIO_SETUP_startTrigger_triggerNo      2
#define _BITPOS_CMD_PROP_RADIO_SETUP_startTrigger_pastTrig      7
#define _NBITS_CMD_PROP_RADIO_SETUP_startTrigger_pastTrig       1
#define _POSITION_CMD_PROP_RADIO_SETUP_condition                13
#define _TYPE_CMD_PROP_RADIO_SETUP_condition                    uint8_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_condition_rule             0
#define _NBITS_CMD_PROP_RADIO_SETUP_condition_rule              4
#define _BITPOS_CMD_PROP_RADIO_SETUP_condition_nSkip            4
#define _NBITS_CMD_PROP_RADIO_SETUP_condition_nSkip             4
#define _POSITION_CMD_PROP_RADIO_SETUP_modulation               14
#define _TYPE_CMD_PROP_RADIO_SETUP_modulation                   uint16_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_modulation_modType         0
#define _NBITS_CMD_PROP_RADIO_SETUP_modulation_modType          3
#define _BITPOS_CMD_PROP_RADIO_SETUP_modulation_deviation       3
#define _NBITS_CMD_PROP_RADIO_SETUP_modulation_deviation        13
#define _POSITION_CMD_PROP_RADIO_SETUP_symbolRate               16
#define _TYPE_CMD_PROP_RADIO_SETUP_symbolRate                   uint32_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_symbolRate_preScale        0
#define _NBITS_CMD_PROP_RADIO_SETUP_symbolRate_preScale         4
#define _BITPOS_CMD_PROP_RADIO_SETUP_symbolRate_rateWord        8
#define _NBITS_CMD_PROP_RADIO_SETUP_symbolRate_rateWord         21
#define _BITPOS_CMD_PROP_RADIO_SETUP_symbolRate_bPdifDecim      29
#define _NBITS_CMD_PROP_RADIO_SETUP_symbolRate_bPdifDecim       1
#define _BITPOS_CMD_PROP_RADIO_SETUP_symbolRate_pdifDecim       30
#define _NBITS_CMD_PROP_RADIO_SETUP_symbolRate_pdifDecim        2
#define _POSITION_CMD_PROP_RADIO_SETUP_rxBw                     20
#define _TYPE_CMD_PROP_RADIO_SETUP_rxBw                         uint8_t
#define _POSITION_CMD_PROP_RADIO_SETUP_preamConf                21
#define _TYPE_CMD_PROP_RADIO_SETUP_preamConf                    uint8_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_preamConf_nPreamBytes      0
#define _NBITS_CMD_PROP_RADIO_SETUP_preamConf_nPreamBytes       6
#define _BITPOS_CMD_PROP_RADIO_SETUP_preamConf_preamMode        6
#define _NBITS_CMD_PROP_RADIO_SETUP_preamConf_preamMode         2
#define _POSITION_CMD_PROP_RADIO_SETUP_formatConf               22
#define _TYPE_CMD_PROP_RADIO_SETUP_formatConf                   uint16_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_formatConf_nSwBits         0
#define _NBITS_CMD_PROP_RADIO_SETUP_formatConf_nSwBits          6
#define _BITPOS_CMD_PROP_RADIO_SETUP_formatConf_bBitReversal    6
#define _NBITS_CMD_PROP_RADIO_SETUP_formatConf_bBitReversal     1
#define _BITPOS_CMD_PROP_RADIO_SETUP_formatConf_bMsbFirst       7
#define _NBITS_CMD_PROP_RADIO_SETUP_formatConf_bMsbFirst        1
#define _BITPOS_CMD_PROP_RADIO_SETUP_formatConf_fecMode         8
#define _NBITS_CMD_PROP_RADIO_SETUP_formatConf_fecMode          4
#define _BITPOS_CMD_PROP_RADIO_SETUP_formatConf_bDigitalAgc     12
#define _NBITS_CMD_PROP_RADIO_SETUP_formatConf_bDigitalAgc      1
#define _BITPOS_CMD_PROP_RADIO_SETUP_formatConf_whitenMode      13
#define _NBITS_CMD_PROP_RADIO_SETUP_formatConf_whitenMode       3
#define _POSITION_CMD_PROP_RADIO_SETUP_config                   24
#define _TYPE_CMD_PROP_RADIO_SETUP_config                       uint16_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_frontEndMode        0
#define _NBITS_CMD_PROP_RADIO_SETUP_config_frontEndMode         3
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_biasMode            3
#define _NBITS_CMD_PROP_RADIO_SETUP_config_biasMode             1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoAdi0Setup        4
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoAdi0Setup         1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoAdi0Trim         5
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoAdi0Trim          1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoAdi0Ovr          6
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoAdi0Ovr           1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoAdi1Setup        7
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoAdi1Setup         1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoAdi1Trim         8
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoAdi1Trim          1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoAdi1Ovr          9
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoAdi1Ovr           1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_bNoFsPowerUp        10
#define _NBITS_CMD_PROP_RADIO_SETUP_config_bNoFsPowerUp         1
#define _BITPOS_CMD_PROP_RADIO_SETUP_config_lnaIbBoost          11
#define _NBITS_CMD_PROP_RADIO_SETUP_config_lnaIbBoost           1
#define _POSITION_CMD_PROP_RADIO_SETUP_txPower                  26
#define _TYPE_CMD_PROP_RADIO_SETUP_txPower                      uint16_t
#define _BITPOS_CMD_PROP_RADIO_SETUP_txPower_IB                 0
#define _NBITS_CMD_PROP_RADIO_SETUP_txPower_IB                  6
#define _BITPOS_CMD_PROP_RADIO_SETUP_txPower_GC                 6
#define _NBITS_CMD_PROP_RADIO_SETUP_txPower_GC                  2
#define _BITPOS_CMD_PROP_RADIO_SETUP_txPower_boost              8
#define _NBITS_CMD_PROP_RADIO_SETUP_txPower_boost               1
#define _BITPOS_CMD_PROP_RADIO_SETUP_txPower_tempCoeff          9
#define _NBITS_CMD_PROP_RADIO_SETUP_txPower_tempCoeff           7
#define _POSITION_CMD_PROP_RADIO_SETUP_pRegOverride             28
#define _TYPE_CMD_PROP_RADIO_SETUP_pRegOverride                 uint32_t*
#define _SIZEOF_CMD_PROP_RADIO_SETUP                            32

#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_commandNo            0
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_commandNo                uint16_t
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_status               2
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_status                   uint16_t
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_pNextOp              4
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_pNextOp                  uint8_t*
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_startTime            8
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_startTime                ratmr_t
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_startTrigger         12
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_startTrigger             uint8_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_triggerType 0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_triggerType 4
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_bEnaCmd   4
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_bEnaCmd    1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_triggerNo 5
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_triggerNo  2
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_pastTrig  7
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_startTrigger_pastTrig   1
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_condition            13
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_condition                uint8_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_condition_rule         0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_condition_rule          4
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_condition_nSkip        4
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_condition_nSkip         4
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_modulation           14
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_modulation               uint16_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_modulation_modType     0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_modulation_modType      3
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_modulation_deviation   3
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_modulation_deviation    13
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_symbolRate           16
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_symbolRate               uint32_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_preScale    0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_preScale     4
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_rateWord    8
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_rateWord     21
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_bPdifDecim  29
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_bPdifDecim   1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_pdifDecim   30
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_symbolRate_pdifDecim    2
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_rxBw                 20
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_rxBw                     uint8_t
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_preamConf            21
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_preamConf                uint8_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_preamConf_nPreamBytes  0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_preamConf_nPreamBytes   6
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_preamConf_preamMode    6
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_preamConf_preamMode     2
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_formatConf           22
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_formatConf               uint16_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_formatConf_nSwBits     0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_formatConf_nSwBits      6
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_formatConf_bBitReversal 6
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_formatConf_bBitReversal 1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_formatConf_bMsbFirst   7
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_formatConf_bMsbFirst    1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_formatConf_fecMode     8
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_formatConf_fecMode      4
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_formatConf_bDigitalAgc 12
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_formatConf_bDigitalAgc  1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_formatConf_whitenMode  13
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_formatConf_whitenMode   3
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_config               24
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_config                   uint16_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_frontEndMode    0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_frontEndMode     3
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_biasMode        3
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_biasMode         1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi0Setup    4
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi0Setup     1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi0Trim     5
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi0Trim      1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi0Ovr      6
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi0Ovr       1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi1Setup    7
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi1Setup     1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi1Trim     8
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi1Trim      1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi1Ovr      9
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoAdi1Ovr       1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_bNoFsPowerUp    10
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_bNoFsPowerUp     1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_config_lnaIbBoost      11
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_config_lnaIbBoost       1
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_txPower              26
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_txPower                  uint16_t
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_txPower_IB             0
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_txPower_IB              6
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_txPower_GC             6
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_txPower_GC              2
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_txPower_boost          8
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_txPower_boost           1
#define _BITPOS_CMD_PROP_RADIO_DIV_SETUP_txPower_tempCoeff      9
#define _NBITS_CMD_PROP_RADIO_DIV_SETUP_txPower_tempCoeff       7
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_pRegOverride         28
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_pRegOverride             uint32_t*
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_centerFreq           32
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_centerFreq               uint16_t
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_intFreq              34
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_intFreq                  int16_t
#define _POSITION_CMD_PROP_RADIO_DIV_SETUP_loDivider            36
#define _TYPE_CMD_PROP_RADIO_DIV_SETUP_loDivider                uint8_t
#define _SIZEOF_CMD_PROP_RADIO_DIV_SETUP                        37

#define _POSITION_CMD_PROP_RX_SNIFF_commandNo                   0
#define _TYPE_CMD_PROP_RX_SNIFF_commandNo                       uint16_t
#define _POSITION_CMD_PROP_RX_SNIFF_status                      2
#define _TYPE_CMD_PROP_RX_SNIFF_status                          uint16_t
#define _POSITION_CMD_PROP_RX_SNIFF_pNextOp                     4
#define _TYPE_CMD_PROP_RX_SNIFF_pNextOp                         uint8_t*
#define _POSITION_CMD_PROP_RX_SNIFF_startTime                   8
#define _TYPE_CMD_PROP_RX_SNIFF_startTime                       ratmr_t
#define _POSITION_CMD_PROP_RX_SNIFF_startTrigger                12
#define _TYPE_CMD_PROP_RX_SNIFF_startTrigger                    uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_startTrigger_triggerType      0
#define _NBITS_CMD_PROP_RX_SNIFF_startTrigger_triggerType       4
#define _BITPOS_CMD_PROP_RX_SNIFF_startTrigger_bEnaCmd          4
#define _NBITS_CMD_PROP_RX_SNIFF_startTrigger_bEnaCmd           1
#define _BITPOS_CMD_PROP_RX_SNIFF_startTrigger_triggerNo        5
#define _NBITS_CMD_PROP_RX_SNIFF_startTrigger_triggerNo         2
#define _BITPOS_CMD_PROP_RX_SNIFF_startTrigger_pastTrig         7
#define _NBITS_CMD_PROP_RX_SNIFF_startTrigger_pastTrig          1
#define _POSITION_CMD_PROP_RX_SNIFF_condition                   13
#define _TYPE_CMD_PROP_RX_SNIFF_condition                       uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_condition_rule                0
#define _NBITS_CMD_PROP_RX_SNIFF_condition_rule                 4
#define _BITPOS_CMD_PROP_RX_SNIFF_condition_nSkip               4
#define _NBITS_CMD_PROP_RX_SNIFF_condition_nSkip                4
#define _POSITION_CMD_PROP_RX_SNIFF_pktConf                     14
#define _TYPE_CMD_PROP_RX_SNIFF_pktConf                         uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_bFsOff                0
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_bFsOff                 1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_bRepeatOk             1
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_bRepeatOk              1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_bRepeatNok            2
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_bRepeatNok             1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_bUseCrc               3
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_bUseCrc                1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_bVarLen               4
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_bVarLen                1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_bChkAddress           5
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_bChkAddress            1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_endType               6
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_endType                1
#define _BITPOS_CMD_PROP_RX_SNIFF_pktConf_filterOp              7
#define _NBITS_CMD_PROP_RX_SNIFF_pktConf_filterOp               1
#define _POSITION_CMD_PROP_RX_SNIFF_rxConf                      15
#define _TYPE_CMD_PROP_RX_SNIFF_rxConf                          uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bAutoFlushIgnored      0
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bAutoFlushIgnored       1
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bAutoFlushCrcErr       1
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bAutoFlushCrcErr        1
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bIncludeHdr            3
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bIncludeHdr             1
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bIncludeCrc            4
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bIncludeCrc             1
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bAppendRssi            5
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bAppendRssi             1
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bAppendTimestamp       6
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bAppendTimestamp        1
#define _BITPOS_CMD_PROP_RX_SNIFF_rxConf_bAppendStatus          7
#define _NBITS_CMD_PROP_RX_SNIFF_rxConf_bAppendStatus           1
#define _POSITION_CMD_PROP_RX_SNIFF_syncWord                    16
#define _TYPE_CMD_PROP_RX_SNIFF_syncWord                        uint32_t
#define _POSITION_CMD_PROP_RX_SNIFF_maxPktLen                   20
#define _TYPE_CMD_PROP_RX_SNIFF_maxPktLen                       uint8_t
#define _POSITION_CMD_PROP_RX_SNIFF_address0                    21
#define _TYPE_CMD_PROP_RX_SNIFF_address0                        uint8_t
#define _POSITION_CMD_PROP_RX_SNIFF_address1                    22
#define _TYPE_CMD_PROP_RX_SNIFF_address1                        uint8_t
#define _POSITION_CMD_PROP_RX_SNIFF_endTrigger                  23
#define _TYPE_CMD_PROP_RX_SNIFF_endTrigger                      uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_endTrigger_triggerType        0
#define _NBITS_CMD_PROP_RX_SNIFF_endTrigger_triggerType         4
#define _BITPOS_CMD_PROP_RX_SNIFF_endTrigger_bEnaCmd            4
#define _NBITS_CMD_PROP_RX_SNIFF_endTrigger_bEnaCmd             1
#define _BITPOS_CMD_PROP_RX_SNIFF_endTrigger_triggerNo          5
#define _NBITS_CMD_PROP_RX_SNIFF_endTrigger_triggerNo           2
#define _BITPOS_CMD_PROP_RX_SNIFF_endTrigger_pastTrig           7
#define _NBITS_CMD_PROP_RX_SNIFF_endTrigger_pastTrig            1
#define _POSITION_CMD_PROP_RX_SNIFF_endTime                     24
#define _TYPE_CMD_PROP_RX_SNIFF_endTime                         ratmr_t
#define _POSITION_CMD_PROP_RX_SNIFF_pQueue                      28
#define _TYPE_CMD_PROP_RX_SNIFF_pQueue                          dataQueue_t*
#define _POSITION_CMD_PROP_RX_SNIFF_pOutput                     32
#define _TYPE_CMD_PROP_RX_SNIFF_pOutput                         uint8_t*
#define _POSITION_CMD_PROP_RX_SNIFF_csConf                      36
#define _TYPE_CMD_PROP_RX_SNIFF_csConf                          uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_csConf_bEnaRssi               0
#define _NBITS_CMD_PROP_RX_SNIFF_csConf_bEnaRssi                1
#define _BITPOS_CMD_PROP_RX_SNIFF_csConf_bEnaCorr               1
#define _NBITS_CMD_PROP_RX_SNIFF_csConf_bEnaCorr                1
#define _BITPOS_CMD_PROP_RX_SNIFF_csConf_operation              2
#define _NBITS_CMD_PROP_RX_SNIFF_csConf_operation               1
#define _BITPOS_CMD_PROP_RX_SNIFF_csConf_busyOp                 3
#define _NBITS_CMD_PROP_RX_SNIFF_csConf_busyOp                  1
#define _BITPOS_CMD_PROP_RX_SNIFF_csConf_idleOp                 4
#define _NBITS_CMD_PROP_RX_SNIFF_csConf_idleOp                  1
#define _BITPOS_CMD_PROP_RX_SNIFF_csConf_timeoutRes             5
#define _NBITS_CMD_PROP_RX_SNIFF_csConf_timeoutRes              1
#define _POSITION_CMD_PROP_RX_SNIFF_rssiThr                     37
#define _TYPE_CMD_PROP_RX_SNIFF_rssiThr                         int8_t
#define _POSITION_CMD_PROP_RX_SNIFF_numRssiIdle                 38
#define _TYPE_CMD_PROP_RX_SNIFF_numRssiIdle                     uint8_t
#define _POSITION_CMD_PROP_RX_SNIFF_numRssiBusy                 39
#define _TYPE_CMD_PROP_RX_SNIFF_numRssiBusy                     uint8_t
#define _POSITION_CMD_PROP_RX_SNIFF_corrPeriod                  40
#define _TYPE_CMD_PROP_RX_SNIFF_corrPeriod                      uint16_t
#define _POSITION_CMD_PROP_RX_SNIFF_corrConfig                  42
#define _TYPE_CMD_PROP_RX_SNIFF_corrConfig                      uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_corrConfig_numCorrInv         0
#define _NBITS_CMD_PROP_RX_SNIFF_corrConfig_numCorrInv          4
#define _BITPOS_CMD_PROP_RX_SNIFF_corrConfig_numCorrBusy        4
#define _NBITS_CMD_PROP_RX_SNIFF_corrConfig_numCorrBusy         4
#define _POSITION_CMD_PROP_RX_SNIFF_csEndTrigger                43
#define _TYPE_CMD_PROP_RX_SNIFF_csEndTrigger                    uint8_t
#define _BITPOS_CMD_PROP_RX_SNIFF_csEndTrigger_triggerType      0
#define _NBITS_CMD_PROP_RX_SNIFF_csEndTrigger_triggerType       4
#define _BITPOS_CMD_PROP_RX_SNIFF_csEndTrigger_bEnaCmd          4
#define _NBITS_CMD_PROP_RX_SNIFF_csEndTrigger_bEnaCmd           1
#define _BITPOS_CMD_PROP_RX_SNIFF_csEndTrigger_triggerNo        5
#define _NBITS_CMD_PROP_RX_SNIFF_csEndTrigger_triggerNo         2
#define _BITPOS_CMD_PROP_RX_SNIFF_csEndTrigger_pastTrig         7
#define _NBITS_CMD_PROP_RX_SNIFF_csEndTrigger_pastTrig          1
#define _POSITION_CMD_PROP_RX_SNIFF_csEndTime                   44
#define _TYPE_CMD_PROP_RX_SNIFF_csEndTime                       ratmr_t
#define _POSITION_CMD_PROP_RX_SNIFF_carrierSense                36
#define _TYPE_CMD_PROP_RX_SNIFF_carrierSense                    uint8_t
#define _SIZEOF_CMD_PROP_RX_SNIFF                               48

#define _POSITION_CMD_PROP_RX_ADV_SNIFF_commandNo               0
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_commandNo                   uint16_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_status                  2
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_status                      uint16_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_pNextOp                 4
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_pNextOp                     uint8_t*
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_startTime               8
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_startTime                   ratmr_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_startTrigger            12
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_startTrigger                uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_startTrigger_triggerType  0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_startTrigger_triggerType   4
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_startTrigger_bEnaCmd      4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_startTrigger_bEnaCmd       1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_startTrigger_triggerNo    5
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_startTrigger_triggerNo     2
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_startTrigger_pastTrig     7
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_startTrigger_pastTrig      1
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_condition               13
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_condition                   uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_condition_rule            0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_condition_rule             4
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_condition_nSkip           4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_condition_nSkip            4
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_pktConf                 14
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_pktConf                     uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_bFsOff            0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_bFsOff             1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_bRepeatOk         1
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_bRepeatOk          1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_bRepeatNok        2
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_bRepeatNok         1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_bUseCrc           3
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_bUseCrc            1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_bCrcIncSw         4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_bCrcIncSw          1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_bCrcIncHdr        5
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_bCrcIncHdr         1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_endType           6
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_endType            1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_pktConf_filterOp          7
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_pktConf_filterOp           1
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_rxConf                  15
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_rxConf                      uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAutoFlushIgnored  0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAutoFlushIgnored   1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAutoFlushCrcErr   1
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAutoFlushCrcErr    1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bIncludeHdr        3
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bIncludeHdr         1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bIncludeCrc        4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bIncludeCrc         1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAppendRssi        5
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAppendRssi         1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAppendTimestamp   6
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAppendTimestamp    1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAppendStatus      7
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_rxConf_bAppendStatus       1
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_syncWord0               16
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_syncWord0                   uint32_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_syncWord1               20
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_syncWord1                   uint32_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_maxPktLen               24
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_maxPktLen                   uint16_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_hdrConf                 26
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_hdrConf                     uint16_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_hdrConf_numHdrBits        0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_hdrConf_numHdrBits         6
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_hdrConf_lenPos            6
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_hdrConf_lenPos             5
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_hdrConf_numLenBits        11
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_hdrConf_numLenBits         5
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_addrConf                28
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_addrConf                    uint16_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_addrConf_addrType         0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_addrConf_addrType          1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_addrConf_addrSize         1
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_addrConf_addrSize          5
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_addrConf_addrPos          6
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_addrConf_addrPos           5
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_addrConf_numAddr          11
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_addrConf_numAddr           5
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_lenOffset               30
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_lenOffset                   int8_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_endTrigger              31
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_endTrigger                  uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_endTrigger_triggerType    0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_endTrigger_triggerType     4
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_endTrigger_bEnaCmd        4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_endTrigger_bEnaCmd         1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_endTrigger_triggerNo      5
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_endTrigger_triggerNo       2
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_endTrigger_pastTrig       7
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_endTrigger_pastTrig        1
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_endTime                 32
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_endTime                     ratmr_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_pAddr                   36
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_pAddr                       uint8_t*
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_pQueue                  40
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_pQueue                      dataQueue_t*
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_pOutput                 44
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_pOutput                     uint8_t*
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_csConf                  48
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_csConf                      uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csConf_bEnaRssi           0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csConf_bEnaRssi            1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csConf_bEnaCorr           1
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csConf_bEnaCorr            1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csConf_operation          2
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csConf_operation           1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csConf_busyOp             3
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csConf_busyOp              1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csConf_idleOp             4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csConf_idleOp              1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csConf_timeoutRes         5
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csConf_timeoutRes          1
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_rssiThr                 49
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_rssiThr                     int8_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_numRssiIdle             50
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_numRssiIdle                 uint8_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_numRssiBusy             51
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_numRssiBusy                 uint8_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_corrPeriod              52
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_corrPeriod                  uint16_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_corrConfig              54
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_corrConfig                  uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_corrConfig_numCorrInv     0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_corrConfig_numCorrInv      4
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_corrConfig_numCorrBusy    4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_corrConfig_numCorrBusy     4
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_csEndTrigger            55
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_csEndTrigger                uint8_t
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_triggerType  0
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_triggerType   4
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_bEnaCmd      4
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_bEnaCmd       1
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_triggerNo    5
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_triggerNo     2
#define _BITPOS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_pastTrig     7
#define _NBITS_CMD_PROP_RX_ADV_SNIFF_csEndTrigger_pastTrig      1
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_csEndTime               56
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_csEndTime                   ratmr_t
#define _POSITION_CMD_PROP_RX_ADV_SNIFF_carrierSense            48
#define _TYPE_CMD_PROP_RX_ADV_SNIFF_carrierSense                uint8_t
#define _SIZEOF_CMD_PROP_RX_ADV_SNIFF                           60

#define _POSITION_CMD_PROP_SET_LEN_commandNo                    0
#define _TYPE_CMD_PROP_SET_LEN_commandNo                        uint16_t
#define _POSITION_CMD_PROP_SET_LEN_rxLen                        2
#define _TYPE_CMD_PROP_SET_LEN_rxLen                            uint16_t
#define _SIZEOF_CMD_PROP_SET_LEN                                4

#define _POSITION_CMD_PROP_RESTART_RX_commandNo                 0
#define _TYPE_CMD_PROP_RESTART_RX_commandNo                     uint16_t
#define _SIZEOF_CMD_PROP_RESTART_RX                             2

#define _POSITION_propRxOutput_nRxOk                            0
#define _TYPE_propRxOutput_nRxOk                                uint16_t
#define _POSITION_propRxOutput_nRxNok                           2
#define _TYPE_propRxOutput_nRxNok                               uint16_t
#define _POSITION_propRxOutput_nRxIgnored                       4
#define _TYPE_propRxOutput_nRxIgnored                           uint8_t
#define _POSITION_propRxOutput_nRxStopped                       5
#define _TYPE_propRxOutput_nRxStopped                           uint8_t
#define _POSITION_propRxOutput_nRxBufFull                       6
#define _TYPE_propRxOutput_nRxBufFull                           uint8_t
#define _POSITION_propRxOutput_lastRssi                         7
#define _TYPE_propRxOutput_lastRssi                             int8_t
#define _POSITION_propRxOutput_timeStamp                        8
#define _TYPE_propRxOutput_timeStamp                            ratmr_t
#define _SIZEOF_propRxOutput                                    12

#define _POSITION_propRxStatus_status                           0
#define _TYPE_propRxStatus_status                               uint8_t
#define _BITPOS_propRxStatus_status_addressInd                  0
#define _NBITS_propRxStatus_status_addressInd                   5
#define _BITPOS_propRxStatus_status_syncWordId                  5
#define _NBITS_propRxStatus_status_syncWordId                   1
#define _BITPOS_propRxStatus_status_result                      6
#define _NBITS_propRxStatus_status_result                       2
#define _SIZEOF_propRxStatus                                    1

#endif
