#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M3{1,0,5.2,2
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3.dep
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3: package/package_ti.drivers.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/package -fr=./package/lib/lib/drivers_cc26xxware/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/package -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/package -fr=./package/lib/lib/drivers_cc26xxware/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.sem3: package/package_ti.drivers.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/package -fr=./package/lib/lib/drivers_cc26xxware/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/package -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/package -fr=./package/lib/lib/drivers_cc26xxware/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3.dep
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3: ./crypto/CryptoCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./crypto -fr=./package/lib/lib/drivers_cc26xxware/./crypto -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./crypto -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./crypto -fr=./package/lib/lib/drivers_cc26xxware/./crypto
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.sem3: ./crypto/CryptoCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./crypto -fr=./package/lib/lib/drivers_cc26xxware/./crypto -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./crypto -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./crypto -fr=./package/lib/lib/drivers_cc26xxware/./crypto
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3.dep
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3: ./dma/UDMACC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./dma -fr=./package/lib/lib/drivers_cc26xxware/./dma -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./dma -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./dma -fr=./package/lib/lib/drivers_cc26xxware/./dma
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.sem3: ./dma/UDMACC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./dma -fr=./package/lib/lib/drivers_cc26xxware/./dma -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./dma -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./dma -fr=./package/lib/lib/drivers_cc26xxware/./dma
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/I2C.oem3.dep
package/lib/lib/drivers_cc26xxware/I2C.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/I2C.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/I2C.oem3: I2C.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/I2C.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/I2C.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/I2C.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/I2C.sem3: I2C.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/I2C.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/I2C.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3.dep
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3: ./i2c/I2CCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./i2c -fr=./package/lib/lib/drivers_cc26xxware/./i2c -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./i2c -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./i2c -fr=./package/lib/lib/drivers_cc26xxware/./i2c
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.sem3: ./i2c/I2CCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./i2c -fr=./package/lib/lib/drivers_cc26xxware/./i2c -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./i2c -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./i2c -fr=./package/lib/lib/drivers_cc26xxware/./i2c
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3.dep
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3: ./lcd/LCDDogm1286.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./lcd -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.sem3: ./lcd/LCDDogm1286.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./lcd -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3.dep
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3: ./lcd/LCDDogm1286_util.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./lcd -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.sem3: ./lcd/LCDDogm1286_util.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./lcd -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./lcd -fr=./package/lib/lib/drivers_cc26xxware/./lcd
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3.dep
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3: ./pin/PINCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./pin -fr=./package/lib/lib/drivers_cc26xxware/./pin -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./pin -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./pin -fr=./package/lib/lib/drivers_cc26xxware/./pin
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.sem3: ./pin/PINCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./pin -fr=./package/lib/lib/drivers_cc26xxware/./pin -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./pin -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./pin -fr=./package/lib/lib/drivers_cc26xxware/./pin
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/SPI.oem3.dep
package/lib/lib/drivers_cc26xxware/SPI.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/SPI.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/SPI.oem3: SPI.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/SPI.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/SPI.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/SPI.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/SPI.sem3: SPI.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/SPI.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/SPI.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3.dep
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3: ./spi/SPICC26XXDMA.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./spi -fr=./package/lib/lib/drivers_cc26xxware/./spi -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./spi -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./spi -fr=./package/lib/lib/drivers_cc26xxware/./spi
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.sem3: ./spi/SPICC26XXDMA.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./spi -fr=./package/lib/lib/drivers_cc26xxware/./spi -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./spi -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./spi -fr=./package/lib/lib/drivers_cc26xxware/./spi
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/UART.oem3.dep
package/lib/lib/drivers_cc26xxware/UART.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/UART.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/UART.oem3: UART.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/UART.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/UART.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/UART.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/UART.sem3: UART.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware -fr=./package/lib/lib/drivers_cc26xxware
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/UART.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/UART.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3.dep
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3.dep: ;
endif

package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3: ./uart/UARTCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./uart -fr=./package/lib/lib/drivers_cc26xxware/./uart -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./uart -s oem3 $< -C   -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./uart -fr=./package/lib/lib/drivers_cc26xxware/./uart
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.sem3: | .interfaces
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.sem3: ./uart/UARTCC26XX.c lib/drivers_cc26xxware.aem3.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem3 -n $< ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./uart -fr=./package/lib/lib/drivers_cc26xxware/./uart -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/drivers_cc26xxware/./uart -s oem3 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M3 --abi=eabi -eo.oem3 -ea.sem3  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M3 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/cc26xxware_2_21_01_15600 -Dxdc_runtime_Log_DISABLE_ALL -Dxdc_runtime_Assert_DISABLE_ALL  $(XDCINCS) -I$(ti.targets.arm.elf.M3.rootDir)/include/rts -I$(ti.targets.arm.elf.M3.rootDir)/include  -fs=./package/lib/lib/drivers_cc26xxware/./uart -fr=./package/lib/lib/drivers_cc26xxware/./uart
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.sem3: export C_DIR=
package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.sem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 ::
	-$(RM) package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/I2C.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/SPI.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/UART.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3
	-$(RM) package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/I2C.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/SPI.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/UART.sem3
	-$(RM) package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.sem3

lib/drivers_cc26xxware.aem3: package/lib/lib/drivers_cc26xxware/package/package_ti.drivers.oem3 package/lib/lib/drivers_cc26xxware/./crypto/CryptoCC26XX.oem3 package/lib/lib/drivers_cc26xxware/./dma/UDMACC26XX.oem3 package/lib/lib/drivers_cc26xxware/I2C.oem3 package/lib/lib/drivers_cc26xxware/./i2c/I2CCC26XX.oem3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286.oem3 package/lib/lib/drivers_cc26xxware/./lcd/LCDDogm1286_util.oem3 package/lib/lib/drivers_cc26xxware/./pin/PINCC26XX.oem3 package/lib/lib/drivers_cc26xxware/SPI.oem3 package/lib/lib/drivers_cc26xxware/./spi/SPICC26XXDMA.oem3 package/lib/lib/drivers_cc26xxware/UART.oem3 package/lib/lib/drivers_cc26xxware/./uart/UARTCC26XX.oem3 lib/drivers_cc26xxware.aem3.mak

clean::
	-$(RM) lib/drivers_cc26xxware.aem3.mak
