#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4{1,0,5.2,2
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4.dep
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4.dep: ;
endif

package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4: | .interfaces
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4: package/package_ti.drivers.c lib/power_cc3200_tirtos_instrumented.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/package -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/power_cc3200_tirtos_instrumented/package -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/package -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4: export C_DIR=
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.sem4: | .interfaces
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.sem4: package/package_ti.drivers.c lib/power_cc3200_tirtos_instrumented.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/package -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/package -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/power_cc3200_tirtos_instrumented/package -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/package -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/package
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.sem4: export C_DIR=
package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4.dep
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4.dep: ;
endif

package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4: | .interfaces
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4: ./power/PowerCC3200_tirtos_policy.c lib/power_cc3200_tirtos_instrumented.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c  -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/./power -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/./power -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/power_cc3200_tirtos_instrumented/./power -s oem4 $< -C   -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/./power -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/./power
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4: export C_DIR=
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.sem4: | .interfaces
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.sem4: ./power/PowerCC3200_tirtos_policy.c lib/power_cc3200_tirtos_instrumented.aem4.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clem4 -n $< ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armcl -c -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/./power -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/./power -fc $<
	$(MKDEP) -a $@.dep -p package/lib/lib/power_cc3200_tirtos_instrumented/./power -s oem4 $< -C  -n -s --symdebug:none -qq -pdsw225 --endian=little -mv7M4 --float_support=vfplib --abi=eabi -eo.oem4 -ea.sem4  -ms -g --gcc --define=ccs  -Dxdc_target_name__=M4 -Dxdc_target_types__=ti/targets/arm/elf/std.h -Dxdc_bld__profile_release -Dxdc_bld__vers_1_0_5_2_2 -O2  -I/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/CC3200_driverlib_1.1.0 -DCCWARE  -Dxdc_runtime_Assert_DISABLE_CONDITIONAL_ASSERT -DDebugP_ASSERT_ENABLED -DDebugP_LOG_ENABLED  $(XDCINCS) -I$(ti.targets.arm.elf.M4.rootDir)/include/rts -I$(ti.targets.arm.elf.M4.rootDir)/include  -fs=./package/lib/lib/power_cc3200_tirtos_instrumented/./power -fr=./package/lib/lib/power_cc3200_tirtos_instrumented/./power
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.sem4: export C_DIR=
package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.sem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 ::
	-$(RM) package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4
	-$(RM) package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4
	-$(RM) package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.sem4
	-$(RM) package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.sem4

lib/power_cc3200_tirtos_instrumented.aem4: package/lib/lib/power_cc3200_tirtos_instrumented/package/package_ti.drivers.oem4 package/lib/lib/power_cc3200_tirtos_instrumented/./power/PowerCC3200_tirtos_policy.oem4 lib/power_cc3200_tirtos_instrumented.aem4.mak

clean::
	-$(RM) lib/power_cc3200_tirtos_instrumented.aem4.mak
