#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sysbios/hal
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/utils.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/utils.js
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xdc.tci:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xdc.tci
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/template.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/template.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/om2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/om2.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/xmlgen2.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/Warnings.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/Warnings.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/IPackage.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/IPackage.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/package.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Clock.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Clock.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Trace.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/services/global/Trace.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/bld.js:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/bld.js
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/BuildEnvironment.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/PackageContents.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/_gen.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Library.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Executable.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Repository.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Configuration.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Configuration.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Script.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Script.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Manifest.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Manifest.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/Utils.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget2.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget2.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget3.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITarget3.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/ITargetFilter.xs
/db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/package.xs:
package.mak: /db/rtree/library/trees/xdcprod/xdcprod-u33/product/xdccore/Linux/xdctools_3_31_01_33_core/packages/xdc/bld/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/bios.bld:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/bios.bld
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_large.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_large.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_float.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/C28_float.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/IArm.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/_utils.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/_utils.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Linux86.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Linux86.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Mingw.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/Mingw.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv6.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/GCArmv7A.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/IM.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/IM.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M3.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M3.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/M4F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A8F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A8F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A9F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A9F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A15F.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/A15F.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/package.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/ITarget.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/ITarget.xs
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/package.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/package.xs
package.mak: package.bld
/db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/sysbios/Build.xs:
package.mak: /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/sysbios/Build.xs
endif

ti.targets.arm.elf.M3.rootDir ?= /db/vendors/ti/arm/5.2.2/Linux
ti.targets.arm.elf.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/ti/targets/arm/elf/
ti.targets.arm.elf.M4.rootDir ?= /db/vendors/ti/arm/5.2.2/Linux
gnu.targets.arm.M3.rootDir ?= /db/vendors/linaro/gcc-arm-none-eabi-4_8-2014q3
gnu.targets.arm.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/gnu/targets/arm/
gnu.targets.arm.M4.rootDir ?= /db/vendors/linaro/gcc-arm-none-eabi-4_8-2014q3
iar.targets.arm.M3.rootDir ?= /db/vendors/iar/arm/7.40.1a/Linux
iar.targets.arm.packageBase ?= /db/vtree/library/trees/zumaprod/zumaprod-g06/tirtos_simplelink_2_13_00_06/products/bios_6_42_00_08/packages/iar/targets/arm/
iar.targets.arm.M4.rootDir ?= /db/vendors/iar/arm/7.40.1a/Linux
.PRECIOUS: $(XDCCFGDIR)/%.oem3
.PHONY: all,em3 .dlls,em3 .executables,em3 test,em3
all,em3: .executables,em3
.executables,em3: .libraries,em3
.executables,em3: .dlls,em3
.dlls,em3: .libraries,em3
.libraries,em3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em3
	@$(ECHO) xdc .executables,em3
	@$(ECHO) xdc .libraries,em3
	@$(ECHO) xdc .dlls,em3

.PRECIOUS: $(XDCCFGDIR)/%.oem4
.PHONY: all,em4 .dlls,em4 .executables,em4 test,em4
all,em4: .executables,em4
.executables,em4: .libraries,em4
.executables,em4: .dlls,em4
.dlls,em4: .libraries,em4
.libraries,em4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4
	@$(ECHO) xdc .executables,em4
	@$(ECHO) xdc .libraries,em4
	@$(ECHO) xdc .dlls,em4

.PRECIOUS: $(XDCCFGDIR)/%.om3g
.PHONY: all,m3g .dlls,m3g .executables,m3g test,m3g
all,m3g: .executables,m3g
.executables,m3g: .libraries,m3g
.executables,m3g: .dlls,m3g
.dlls,m3g: .libraries,m3g
.libraries,m3g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m3g
	@$(ECHO) xdc .executables,m3g
	@$(ECHO) xdc .libraries,m3g
	@$(ECHO) xdc .dlls,m3g

.PRECIOUS: $(XDCCFGDIR)/%.om4g
.PHONY: all,m4g .dlls,m4g .executables,m4g test,m4g
all,m4g: .executables,m4g
.executables,m4g: .libraries,m4g
.executables,m4g: .dlls,m4g
.dlls,m4g: .libraries,m4g
.libraries,m4g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4g
	@$(ECHO) xdc .executables,m4g
	@$(ECHO) xdc .libraries,m4g
	@$(ECHO) xdc .dlls,m4g

.PRECIOUS: $(XDCCFGDIR)/%.orm3
.PHONY: all,rm3 .dlls,rm3 .executables,rm3 test,rm3
all,rm3: .executables,rm3
.executables,rm3: .libraries,rm3
.executables,rm3: .dlls,rm3
.dlls,rm3: .libraries,rm3
.libraries,rm3: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm3
	@$(ECHO) xdc .executables,rm3
	@$(ECHO) xdc .libraries,rm3
	@$(ECHO) xdc .dlls,rm3

.PRECIOUS: $(XDCCFGDIR)/%.orm4
.PHONY: all,rm4 .dlls,rm4 .executables,rm4 test,rm4
all,rm4: .executables,rm4
.executables,rm4: .libraries,rm4
.executables,rm4: .dlls,rm4
.dlls,rm4: .libraries,rm4
.libraries,rm4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,rm4
	@$(ECHO) xdc .executables,rm4
	@$(ECHO) xdc .libraries,rm4
	@$(ECHO) xdc .dlls,rm4


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sysbios.hal.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sysbios.hal" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sysbios.hal $@

.libraries,em3 .libraries: lib/sysbios/debug/ti.sysbios.hal.aem3

-include lib/sysbios/debug/ti.sysbios.hal.aem3.mak
lib/sysbios/debug/ti.sysbios.hal.aem3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.oem3  into $@ ...
	$(ti.targets.arm.elf.M3.rootDir)/bin/armar  rq $@   package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.oem3 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.oem3 
lib/sysbios/debug/ti.sysbios.hal.aem3: export C_DIR=
lib/sysbios/debug/ti.sysbios.hal.aem3: PATH:=$(ti.targets.arm.elf.M3.rootDir)/bin/:$(PATH)

clean,em3 clean::
	-$(RM) lib/sysbios/debug/ti.sysbios.hal.aem3
.libraries,em4 .libraries: lib/sysbios/debug/ti.sysbios.hal.aem4

-include lib/sysbios/debug/ti.sysbios.hal.aem4.mak
lib/sysbios/debug/ti.sysbios.hal.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.oem4 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.oem4 
lib/sysbios/debug/ti.sysbios.hal.aem4: export C_DIR=
lib/sysbios/debug/ti.sysbios.hal.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/sysbios/debug/ti.sysbios.hal.aem4
.libraries,m3g .libraries: lib/sysbios/debug/ti.sysbios.hal.am3g

-include lib/sysbios/debug/ti.sysbios.hal.am3g.mak
lib/sysbios/debug/ti.sysbios.hal.am3g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.om3g  into $@ ...
	$(gnu.targets.arm.M3.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.om3g package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.om3g 
lib/sysbios/debug/ti.sysbios.hal.am3g: export LD_LIBRARY_PATH=

clean,m3g clean::
	-$(RM) lib/sysbios/debug/ti.sysbios.hal.am3g
.libraries,m4g .libraries: lib/sysbios/debug/ti.sysbios.hal.am4g

-include lib/sysbios/debug/ti.sysbios.hal.am4g.mak
lib/sysbios/debug/ti.sysbios.hal.am4g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.om4g  into $@ ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.om4g package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.om4g 
lib/sysbios/debug/ti.sysbios.hal.am4g: export LD_LIBRARY_PATH=

clean,m4g clean::
	-$(RM) lib/sysbios/debug/ti.sysbios.hal.am4g
.libraries,rm3 .libraries: lib/sysbios/debug/ti.sysbios.hal.arm3

-include lib/sysbios/debug/ti.sysbios.hal.arm3.mak
lib/sysbios/debug/ti.sysbios.hal.arm3: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.orm3  into $@ ...
	LC_ALL=C $(iar.targets.arm.M3.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.orm3 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.orm3 

clean,rm3 clean::
	-$(RM) lib/sysbios/debug/ti.sysbios.hal.arm3
.libraries,rm4 .libraries: lib/sysbios/debug/ti.sysbios.hal.arm4

-include lib/sysbios/debug/ti.sysbios.hal.arm4.mak
lib/sysbios/debug/ti.sysbios.hal.arm4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.orm4  into $@ ...
	LC_ALL=C $(iar.targets.arm.M4.rootDir)/bin/iarchive --silent -o $@   package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.orm4 package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.orm4 

clean,rm4 clean::
	-$(RM) lib/sysbios/debug/ti.sysbios.hal.arm4
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
package_ti.sysbios.hal.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.oem3
package_ti.sysbios.hal.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.sem3
Cache.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.oem3
Cache.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.sem3
CacheNull.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.oem3
CacheNull.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.sem3
Core.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.oem3
Core.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.sem3
CoreNull.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.oem3
CoreNull.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.sem3
Hwi.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.oem3
Hwi.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.sem3
Hwi_stack.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.oem3
Hwi_stack.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.sem3
Hwi_startup.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.oem3
Hwi_startup.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.sem3
Power.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.oem3
Power.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.sem3
PowerNull.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.oem3
PowerNull.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.sem3
Seconds.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.oem3
Seconds.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.sem3
SecondsCallback.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.oem3
SecondsCallback.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.sem3
SecondsClock.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.oem3
SecondsClock.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.sem3
Timer.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.oem3
Timer.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.sem3
TimerNull.oem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.oem3
TimerNull.sem3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.sem3
package_ti.sysbios.hal.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.oem4
package_ti.sysbios.hal.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.sem4
Cache.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.oem4
Cache.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.sem4
CacheNull.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.oem4
CacheNull.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.sem4
Core.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.oem4
Core.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.sem4
CoreNull.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.oem4
CoreNull.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.sem4
Hwi.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.oem4
Hwi.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.sem4
Hwi_stack.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.oem4
Hwi_stack.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.sem4
Hwi_startup.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.oem4
Hwi_startup.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.sem4
Power.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.oem4
Power.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.sem4
PowerNull.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.oem4
PowerNull.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.sem4
Seconds.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.oem4
Seconds.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.sem4
SecondsCallback.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.oem4
SecondsCallback.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.sem4
SecondsClock.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.oem4
SecondsClock.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.sem4
Timer.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.oem4
Timer.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.sem4
TimerNull.oem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.oem4
TimerNull.sem4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.sem4
package_ti.sysbios.hal.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.om3g
package_ti.sysbios.hal.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.sm3g
Cache.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.om3g
Cache.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.sm3g
CacheNull.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.om3g
CacheNull.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.sm3g
Core.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.om3g
Core.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.sm3g
CoreNull.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.om3g
CoreNull.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.sm3g
Hwi.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.om3g
Hwi.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.sm3g
Hwi_stack.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.om3g
Hwi_stack.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.sm3g
Hwi_startup.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.om3g
Hwi_startup.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.sm3g
Power.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.om3g
Power.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.sm3g
PowerNull.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.om3g
PowerNull.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.sm3g
Seconds.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.om3g
Seconds.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.sm3g
SecondsCallback.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.om3g
SecondsCallback.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.sm3g
SecondsClock.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.om3g
SecondsClock.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.sm3g
Timer.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.om3g
Timer.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.sm3g
TimerNull.om3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.om3g
TimerNull.sm3g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.sm3g
package_ti.sysbios.hal.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.om4g
package_ti.sysbios.hal.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.sm4g
Cache.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.om4g
Cache.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.sm4g
CacheNull.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.om4g
CacheNull.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.sm4g
Core.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.om4g
Core.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.sm4g
CoreNull.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.om4g
CoreNull.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.sm4g
Hwi.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.om4g
Hwi.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.sm4g
Hwi_stack.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.om4g
Hwi_stack.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.sm4g
Hwi_startup.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.om4g
Hwi_startup.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.sm4g
Power.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.om4g
Power.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.sm4g
PowerNull.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.om4g
PowerNull.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.sm4g
Seconds.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.om4g
Seconds.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.sm4g
SecondsCallback.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.om4g
SecondsCallback.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.sm4g
SecondsClock.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.om4g
SecondsClock.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.sm4g
Timer.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.om4g
Timer.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.sm4g
TimerNull.om4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.om4g
TimerNull.sm4g,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.sm4g
package_ti.sysbios.hal.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.orm3
package_ti.sysbios.hal.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.srm3
Cache.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.orm3
Cache.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.srm3
CacheNull.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.orm3
CacheNull.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.srm3
Core.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.orm3
Core.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.srm3
CoreNull.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.orm3
CoreNull.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.srm3
Hwi.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.orm3
Hwi.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.srm3
Hwi_stack.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.orm3
Hwi_stack.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.srm3
Hwi_startup.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.orm3
Hwi_startup.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.srm3
Power.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.orm3
Power.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.srm3
PowerNull.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.orm3
PowerNull.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.srm3
Seconds.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.orm3
Seconds.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.srm3
SecondsCallback.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.orm3
SecondsCallback.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.srm3
SecondsClock.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.orm3
SecondsClock.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.srm3
Timer.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.orm3
Timer.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.srm3
TimerNull.orm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.orm3
TimerNull.srm3,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.srm3
package_ti.sysbios.hal.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.orm4
package_ti.sysbios.hal.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/package/package_ti.sysbios.hal.srm4
Cache.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.orm4
Cache.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Cache.srm4
CacheNull.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.orm4
CacheNull.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CacheNull.srm4
Core.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.orm4
Core.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Core.srm4
CoreNull.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.orm4
CoreNull.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/CoreNull.srm4
Hwi.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.orm4
Hwi.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi.srm4
Hwi_stack.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.orm4
Hwi_stack.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_stack.srm4
Hwi_startup.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.orm4
Hwi_startup.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Hwi_startup.srm4
Power.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.orm4
Power.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Power.srm4
PowerNull.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.orm4
PowerNull.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/PowerNull.srm4
Seconds.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.orm4
Seconds.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Seconds.srm4
SecondsCallback.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.orm4
SecondsCallback.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsCallback.srm4
SecondsClock.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.orm4
SecondsClock.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/SecondsClock.srm4
Timer.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.orm4
Timer.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/Timer.srm4
TimerNull.orm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.orm4
TimerNull.srm4,copy : package/lib/lib/sysbios/debug/ti.sysbios.hal/TimerNull.srm4

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sysbios_hal
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sysbios_hal.tar.dep
-include package/rel/ti_sysbios_hal.tar.rcl.dep
endif
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: package/package.bld.xml
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: package/build.cfg
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: package.bld
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Hwi__epilogue.h
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Hwi__prologue.h
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Core__epilogue.h
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Core__prologue.h
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Hwi.xml
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Timer.xml
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Cache.xml
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Seconds.xml
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Seconds.xdt
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: lib/sysbios/debug/ti.sysbios.hal.aem3
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: package/package_ti.sysbios.hal.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Cache.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: CacheNull.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Core.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: CoreNull.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Hwi.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Hwi_stack.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Hwi_startup.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Power.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: PowerNull.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Seconds.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: SecondsCallback.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: SecondsClock.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: Timer.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: TimerNull.c
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: lib/sysbios/debug/ti.sysbios.hal.aem4
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: lib/sysbios/debug/ti.sysbios.hal.am3g
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: lib/sysbios/debug/ti.sysbios.hal.am4g
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: lib/sysbios/debug/ti.sysbios.hal.arm3
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: lib/sysbios/debug/ti.sysbios.hal.arm4
package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_sysbios_hal.tar: package/rel/ti_sysbios_hal.xdc.inc package/rel/ti_sysbios_hal/ti/sysbios/hal/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sysbios_hal.xdc.inc,package/rel/ti_sysbios_hal.tar.dep, ti/sysbios/libFilter.xs)


release release,ti_sysbios_hal: all ti_sysbios_hal.tar
clean:: .clean
	-$(RM) ti_sysbios_hal.tar
	-$(RM) package/rel/ti_sysbios_hal.xdc.inc
	-$(RM) package/rel/ti_sysbios_hal.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/sysbios))
    $(shell $(MKDIR) lib/sysbios)
endif
ifeq (,$(wildcard lib/sysbios/debug))
    $(shell $(MKDIR) lib/sysbios/debug)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/sysbios))
    $(shell $(MKDIR) package/lib/lib/sysbios)
endif
ifeq (,$(wildcard package/lib/lib/sysbios/debug))
    $(shell $(MKDIR) package/lib/lib/sysbios/debug)
endif
ifeq (,$(wildcard package/lib/lib/sysbios/debug/ti.sysbios.hal))
    $(shell $(MKDIR) package/lib/lib/sysbios/debug/ti.sysbios.hal)
endif
ifeq (,$(wildcard package/lib/lib/sysbios/debug/ti.sysbios.hal/package))
    $(shell $(MKDIR) package/lib/lib/sysbios/debug/ti.sysbios.hal/package)
endif
endif
clean::
	-$(RMDIR) package


